### ISSUE TITLE
Introduce new Introspection interface for C++ emitter

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#103]
The C++ supported Blob Inspector interface which was generated if command line option '-includeInspectorCode' was present.

This Blob Inspector interface was not generic enough (it relayed on the fact that all table names across all packages are unique). Therefore, the Blob Inspector interface was temporarily disabled in the Zserio release 1.2.0.

This issue is about to introduce new generic Introspection interface which will replace old Blob Inspector interface.

This new Introspection interface should:
- be generated if command line option '-includeIntrospectionCode' is present
- have entry point in root package (be aware of file name clashing)
- offer some kind of iteration interface through all packages, all databases and all tables
- offer the same conversion methods from/to Blob Inspector Tree (=Introspection Tree)

**Comment by mikir** [comment]
Please investigate the new type info feature in Python: https://github.com/ndsev/zserio/issues/329. It would be great if C++ can use something similar.

**Comment by Mi-La** [comment]
Note that "introspection" was renamed to "reflection".
