### ISSUE TITLE
Modern C++ Generator

### ISSUE THREAD

**Issue by PeachOS** [ndsev/zserio#108]
C++11 is a nearly 8 years old standard. It should be the minimum standard for the C++ code that is generated by zserio.

Generating code in a modern standard helps maintaining the code over the next years. Its features should help a lot in an easier implementation of a code generator (templates being a good example here). 

Features like move semantics should make it possible to generate code, that is much easier to use than the current copy-heavy code, which comes out of zserio.

On the other hand, at some point tool support will be quite difficult when running on an older standard. Many C++ tools will warn you about using it.

Some other low hanging fruits for generated zserio code if you do the switch:
- typesafe enum classes to prevent name clashes
- automatic type deduction
- proper use of nullptr

For us switching to C++ 11 would be a requirement to even consider using zserio.

**Comment by mikir** [comment]
Yes, good idea and we support it. The problem is that this will require significant C++ emitter redesign. We will see when we have time to do it...
