### ISSUE TITLE
Add convertion from zserio::BasicArray to std::vector and/or std::array

### ISSUE THREAD

**Issue by 0xDEAD** [ndsev/zserio#110]
When you copy simple arrays of simple types (like zserio::VarUInt32Array) to std containers, you always have to implement a simple loop by yourself. It would be grate to have that in the runtime, so you can just call

VarUInt32Array dataFromStream;
std::vector<uint32_t> myVector = dataFromStream::toStdVector();

**Comment by mikir** [comment]
New C++11 Emitter already uses STL vector. Old C++98 Emitter won't be fixed because it's deprecated.
