### ISSUE TITLE
Remove Warnings

### ISSUE THREAD

**Issue by PeachOS** [ndsev/zserio#112]
The C++ Code, that is generated, gives a lot of compiler warnings.

Some of them are easy to fix, e.g. all of the category "-Wold-style-cast". For that one simply needs to replace the C style casts with C++ style casts (basically static_cast in most cases).

Some others might just be documented as "not relevant" for us or "we have the following good reason to ignore those" (e.g. I don't care too much about C++ 98 compatibiltiy) .

In my opinion it is worth going through all those warnings. Solve them or document what you ignore.

If you need any explicit examples, I can send you a message of course.

**Comment by mikir** [comment]
We pay attention to this but only for several compilers. So, the question is which compiler do you use?

But I agree with that, we should go through all those warnings.

**Comment by PeachOS** [comment]
Ah sorry forgot to mention that. The compiler version was "Apple LLVM version 10.0.0 (clang-1000.11.45.5)" (clang)

I compiled the software with the option `-Weverything`. That option obviously contains a few unnecessary warnings, but it is a good starting point for an overview.

**Comment by mikir** [comment]
I'll close it because warnings have been solved in the meantime for all supported compiler versions.
