### ISSUE TITLE
Wrong Python code for functions with the same name

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#114]
Generated Python code is wrong for the following schema:

```
package functions.structure_parent_child_value;

ChildValue
{
    uint32      val;

    function uint32 getValue()
    {
        return val;
    }
};

ParentValue
{
    ChildValue      childValue;

    // This function has the same name as ChildValue has but there is no clash.
    function uint32 getValue()
    {
        return childValue.getValue();
    }
};
```
Generated Python emitter formats function expression for `ParentValue` wrongly: 

`self.getChildValue().self.funcGetValue()`.

**Comment by Mi-La** [comment]
Not reproducible with current version of zserio master (ebae36e88c7088d0765dd1d92618458212c4e9ac)

**Comment by mikir** [comment]
This is issue has been already fixed during redesign needed for ANTLR4.
