### ISSUE TITLE
[C++ Question] Why is Container not implemented via std::vector?

### ISSUE THREAD

**Issue by nlohmann** [ndsev/zserio#118]
I just debugged a bit into the C++ code generated by an array and realized that it looks like a reimplementation of `std::vector` under the hood. Is there a reason not to use `std::vector`?

**Comment by mikir** [comment]
Yes, this is because of performance optimization of reading from bit stream. During reading, the calling of push_back() method would be very expensive due to copying. Therefore, we need new interface methods get_next_storage() and commit_storage(). Then, we could use placement new operator and avoid copying.

**Comment by mikir** [comment]
Yes, you are right but we were not allowed to use C++11. So, the whole Container thing is just workaround because of this.

Regarding current zserio, generated C++ code (reader part) does not use copy constructors or push_back. So, no copies at all during parsing from the bit stream.

**Comment by nlohmann** [comment]
You are right, I forgot about the limitation. I tried with C++98 and got the same output for both containers (modulo the factor for resizing). I'll have a look at the reader part then.

**Comment by mikir** [comment]
I hope everything will work as expected. :-) Meaning no copying, no push_back. Thank you very much for your effort.

**Comment by nlohmann** [comment]
Looking at the binary reader, it seems that the magic seems to be requesting a pointer to a piece of memory inside the container (say, at index `idx`) and then using this pointer with a placement new when the individual element is read. I think you could achieve the same by using `std::vector::reserve`, and use `*std::vector::operator[](idx)` for that placement new.

I don't doubt the existing approach works - I just want to understand the re-implementation of something that looks like a `std::vector` to me.

**Comment by mikir** [comment]
As far as I remember, the problem with original std::vector was how to update the vector size after placement new. If this would be somehow possible then I would say your approach would be feasible.

Btw, I don't like this re-implementation. I agree that it looks suspicious. If I had known how to implement this using original std::vector, I would have done it so.

**Comment by nlohmann** [comment]
I played around a bit and found the following code works. It uses some C++11 constructs like `= default`, but the idea should be clear. I privately inherited from `std::vector` to add the two required functions `get_next_storage` and `commit_storage`. Instead of reserving memory, returning it to the caller of `get_next_storage` to use it, I added a member `el` instead. This member is default-initialized with the Container, so it is safe to write to its address. `commit_storage` then moves the content to the actual vector.

```cpp
template <typename ELEMENT_TYPE>
class Container : private std::vector<ELEMENT_TYPE>
{
  private:
    // alias for the underlying type
    using vec = std::vector<ELEMENT_TYPE>;

  public:
    // constructor, destructor, and assignment
    Container() = default;
    explicit Container(std::size_t size) : vec(size) {}
    Container(const Container& other) = default;
    ~Container() = default;
    using vec::operator=;

    // vector interface
    using vec::assign;
    using vec::at;
    using vec::back;
    using vec::begin;
    using vec::capacity;
    using vec::clear;
    using vec::empty;
    using vec::end;
    using vec::erase;
    using vec::front;
    using vec::insert;
    using vec::operator[];
    using vec::pop_back;
    using vec::push_back;
    using vec::resize;
    using vec::reserve;
    using vec::size;
    using vec::swap;

    // vector types
    using typename vec::iterator;
    using typename vec::const_iterator;

    // comparison
    bool operator==(const Container& other) const
    {
        return *this == other;
    }

    // return pointer to (allocated) member
    void* get_next_storage()
    {
        return (void*)&el;
    }

    // move changed member to vector (TODO: error handling from original code)
    void commit_storage(void*)
    {
        vec::push_back(std::move(el));
    }

  private:
    // element to use in get_next_storage() / commit_storage()
    ELEMENT_TYPE el {};
};
```

I could compile and run some small examples with it. Maybe this can help simplifying the existing code.

**Comment by mikir** [comment]
I see your point. But I think the problem will be again in `commit_storage()`. `std::move` is again C++11 feature. Moreover, I think it will copy element anyway if the element is not referenced by pointer.

Our solution is fragile and inconvenient but it is direct consequence of two strange requirements: 
* no C++11
* a need to change private member `size` in `std::vector` in new method `commit_storage`

**Comment by fklebert** [comment]
I think the "no C++11" rule does not really exist any longer since we added GRPC support (remember: GRPC requires C++11 or newer), so we should reconsider the general approach of the CPP runtime.

**Comment by Mi-La** [comment]
That's true, but I don't think it's a good approach to add C++11 features on "random" places of C++ generator/runtime while keeping the old internals. Moreover when the old approach works, is somehow hidden from end users and we have other issues to solve ;-).
Note that C++11 is required really only for GRPC and without GRPC the C++ generated code should be still compilable with almost all archaic compilers.
On the other hand, writing a brand new C++11 generator beside the old one would be another question and I would vote for it immediately.

**Comment by fklebert** [comment]
I agree that we should have two separate cpp emitters for that reason...

**Comment by mikir** [comment]
Custom containers will be deleted in new C++11 emitter. Please see issue #108 which is planned to be in the next zserio release.
