### ISSUE TITLE
Provide debug string representation

### ISSUE THREAD

**Issue by nlohmann** [ndsev/zserio#119]
It would be handy to have some kind of debug string representation. This should be trivial for numbers, strings, and enums (as there is already a string representation), and little work to build this recursively. Basically what `DebugString()` is doing for Protobuf.

**Comment by fklebert** [comment]
In addition to the pure debug string representation it would be beneficial if zserio can also load (modified) text (JSON?) and serialize from that. At least we should evaluate this idea during the implementation of the debug string.

**Comment by nlohmann** [comment]
This sounds like a very good addition. But please (!) make it a standardized means to import/export values unlike Protobuf, which supports different JSON flavors (snake case vs. camel case in object keys) and even worse never standardized their `DebugString()` format.

**Comment by fklebert** [comment]
Another feature that would be beneficial in this exercise would be to dump the bitposition of the structure within the binary representation.

**Comment by mikir** [comment]
> In addition to the pure debug string representation it would be beneficial if zserio can also load (modified) text (JSON?) and serialize from that. At least we should evaluate this idea during the implementation of the debug string.

Created a special issue for that: #278.

**Comment by westphal-michael** [comment]
For Java I propose to use the gson library. I'm using the following generic approach using it:

```
package com.harman.nds.live.util;

import com.google.gson.ExclusionStrategy;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import lombok.Getter;

public class GsonObjectStringFormatter {

    @Getter
    private static ExclusionStrategy excludeByteArray = new GsonClassExclusionStrategy(byte[].class);
    @Getter
    private static Gson gson = new GsonBuilder().setExclusionStrategies(excludeByteArray).setPrettyPrinting().create();

    public static String dumpObjectWithGson(Object value) {
        return dumpObjectWithGson("", value);
    }

    public static String dumpObjectWithGson(String prefix, Object value) {
        String s;
        if (prefix == null) {
            s = "";
        } else {
            s = prefix;
        }
        String valueString = gson.toJson(value);
        return String.format("%s\n%s", s, valueString);
    }
}

```

**Comment by mikir** [comment]
Thanks for hint!

**Comment by mikir** [comment]
We have implemented in zserio runtime generic methods to provide debug string representation of given zserio object: `toJsonString()`, `toJsonFile()` and `toJsonStream()`.

Features:
  - Filtering support
    - Depth Filter
    - Array Length Filter
    - Regex Filter
    - Any ‘AND’ combination of filters
    - Possibility to provide custom filter
  - JSON format

**Comment by nlohmann** [comment]
Thanks!

**Comment by jo-me** [comment]
@mikir  is there any documenation or example that shows how this is used in Python?

**Comment by mikir** [comment]
It is enough just to do following:

```
from zserio.debugstring import to_json_stream, to_json_string, to_json_file

obj = SomeZserioObject()
to_json_string(obj)
```

More examples how to call it can be found [here](https://github.com/ndsev/zserio/blob/master/compiler/extensions/python/runtime/tests/test_debugstring.py).

More documentation of Python runtime is available at subdirectory `runtime_libs/python/zserio_apidoc/index.html` directly in runtime zip [here](https://github.com/ndsev/zserio/releases/download/v2.6.0/zserio-2.6.0-runtime-libs.zip). Unfortunately, this must be done currently by hand but we are going to improve integration of Python runtime documentation to GitHub in near future (see issue #395). We will put there some examples as well.

**Comment by mikir** [comment]
Now, online documentation of Zserio runtime libraries is available. More info, please see [#395](https://github.com/ndsev/zserio/issues/395#issuecomment-1134229918). There are even some examples of the most important features. For example, Python [to_json_string()](http://zserio.org/doc/runtime/python/api/zserio.to_json_string.html#zserio.to_json_string) function.
