### ISSUE TITLE
Add bitmasks into zserio language

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#129]
Because new C++ generator will use strongly typed enumerations, no bitmask operations will be possible for enumeration values.

Because of that there is a bitmask extension for C++ enumeration available here https://www.justsoftwaresolutions.co.uk/files/bitmask_operators.hpp under Boost Software License.

This issue is about to start discussion if we should integrate such extension to the zserio or not.

If we integrate bitmask extension into zserio, we will have to solve some problems connected to the generic solution:

1. Result of bitmask operation can be invalid enumeration value. This must be somehow checked. Probably throwing exception would be the best.
1. Zserio compiler does not know which enumeration type contains bitmask values. It would be probably necessary to introduce new directive in the language because of that. Or to introduce new Type bitmask would be even better:
```
bitmask uint16 Permissions
{
    EXECUTABLE = 1,
    READABLE = 2,
    WRITABLE = 4
};
```
3. We must keep in mind solutions for Java and Python as well.

**Comment by BuzaL** [comment]
I think the bitmask issue can be solved if you modify the return values in the hpp mentioned above to return underlying types and accept underlying as first parameter. So no exception handling required + enough to validate the value if setting it to bitmask holder.
2. agree with that. I think the bitmask type describe better what does it for

**Comment by fklebert** [comment]
I would also opt for a separate data type in the language, since it will also be easier to read and use.

**Comment by mikir** [comment]
The current idea is to implement new `bitmask` keyword which allows definition of bitmask together with bit order number (less significant bit has order number 0):

```
bitmask uint8 Permissions
{
    EXECUTABLE:0,
    RESERVED:1,
    READABLE:2,
    WRITABLE:6
};
```

The previous defines the following bit masks:

```
EXECUTABLE = 0x01
RESERVED = 0x02
READABLE =  0x04
WRITABLE = 0x40
```

The following bitmasks are the same as previous one:

```
bitmask uint8 Permissions
{
    EXECUTABLE,
    RESERVED,
    READABLE,
    WRITABLE:6
};
```

```
bitmask uint8 Permissions
{
    EXECUTABLE:0,
    RESERVED,
    READABLE,
    WRITABLE:6
};
```

**Comment by Mi-La** [comment]
Merged to master.
