### ISSUE TITLE
initializeOffsets method does not resize offset arrays

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#13]
initializeOffsets method supposes that the offset array has correct size set by application.

If application fails to resize offset arrays, out of bound exception is thrown. This can be improved and initializeOffsets can resize offset arrays automatically to make application life easier.

**Comment by mikir** [comment]
This can be done only for auto arrays. And be careful that index can be any expression:

```
struct SkipableDictionary
{
    uint32      offsets[];
offsets[@index + 1]:
    DictEntry   entries[];
};
```

**Comment by fklebert** [comment]
Does the fact that an index can be any kind of expression make sense? Why would I want do something like you indicated? Maybe we can just constrain that to a certain use. Like @index and that's it!

**Comment by Mi-La** [comment]
It would make the problem easier. Currently it's possible to have a single offsets array for two or more data arrays. Maybe it's not much important feature however...
Expression with @index only have sense for parameterized types.

**Comment by Mi-La** [comment]
```
struct SkipableDictionary
{
    uint32      offsets[];
offsets[@index]:
    DictEntry   entries[];
offsets[@index + lengthof(entries)]:
    DictEntry   extraEntries[];
};
```
However this example could have sense ...

**Comment by fklebert** [comment]
Really??? I mean that would mean that the `extraEntries` have to have identical size and length as `entries`. That doesn't sound like a valuable feature for me.

**Comment by Mi-La** [comment]
Why should the `extraEntries` have identical size? It can have any type and any size the expression `@index + lengthof(entries)` just says, that offsets to `extraEntries` elements are stored in `offsets` array and start at index `lengthof(entries)` - i.e. just behind the offsets to `entries` elements.
We can even do:
```
struct SkipableDictionary
{
    uint32      offsets[];
    SomeObscureStruct someData;
offsets[0]:
    int32         importantField;
offsets[@index + 1 ]:
    DictEntry   entries[];
offsets[@index + lengthof(entries) + 1] :
    DictEntry   extraEntries[];
};
```
This is the current state. However it is always possible to write it differently if we decide to forbid expressions in 'offset arrays'.

**Comment by fklebert** [comment]
OK, I see. I mixed up the lengthof operator. But still I do not see the real-world use case behind this.
If you need to do something like above, why not use a second list of offsets?
```
struct Test
{
    uint32         offsets[];
    varuint64      labels[];
offsets[0]:
    int32         importantField;
offsets[@index + 1 ]:
    varuint32   entries[];
labels[@index] :
    varuint64   extraEntries[];
};
```

**Comment by mikir** [comment]
Yes, it is just a "fancy" stuff for users. If they want to use '@index' expressions, they can. If they don't want to, they can still use multiple offsets arrays.

If we decide to restrict users, we should have some advantages from this.

Regarding initialization of structure fields, currently there is nothing smart in zserio except of default values. Meaning, if you define field without default value in language (arrays can't have defaults at the moment), you must set this field. Keeping this philosophy, zserio should NOT resize offsets field automatically until we introduce something like default or arrays:

```
struct SkipableDictionary
{
    uint32      offsets[lengthof(entries)] = {0};
offsets[@index]:
    DictEntry   entries[];
};
```

And this looks strange as well.

My suggestion is just to keep it as it is and document it properly. Applications must be aware that ALL fields without defaults must be initialized properly. initializeOffsets() just helps to fill correct elements then. We might want to rename it to fillOffsets() to eliminate confusions.

And if we leave it as it is, we might leave '@index' expressions as well. Just not to make any restrictions if we don't need them.

**Comment by fklebert** [comment]
OK, then let's properly document the use of `initializeOffsets` if we anyhow cannot make it work automatically.

**Comment by mikir** [comment]
Description of indexed offsets has been improved in ZserioLanguageOverview and ZserioEncodingGuide documents to be clear that offset arrays are not resized automatically.
