### ISSUE TITLE
Implicit array cannot have indexed offsets

### ISSUE THREAD

**Issue by Mi-La** [ndsev/zserio#131]
Zserio runtime libraries and generators templates don't expect implicit arrays to be indexed. Therefore we should either forbid it in the core or implement it correctly in all generators.
```
struct IndexedImplicitArray
{
    uint32 offsets[];
offsets[@index]: // should be forbidden!
    implicit uint32 values[];
};
```

**Comment by 0xDEAD** [comment]
Definitively implement in all generators!
Implicit arrays are a big win for readability, not only the schema but also the filling code (no more `x.setNumOffsets(x.getOffsets().size());`)

**Comment by mikir** [comment]
I think you mean auto arrays. That's ok. We think about implicit arrays which do not have encoded size in the biit stream. Such arrays must be at the end of stream only and it does not have big sense to enable offsets for them.

**Comment by 0xDEAD** [comment]
Ahh, sorry, misunderstanding...

**Comment by mikir** [comment]
No problem. :-)
