### ISSUE TITLE
GRPC service endpoints are language dependent

### ISSUE THREAD

**Issue by chagui** [ndsev/zserio#151]
Generated service endpoints are based on the package name of the generated code. Because C++ package name structure differs from Python and Java they will have different (incompatible) endpoints. This prevent interoperability between client and server written in different languages.

For instance for the code snippet bellow ZSerio (1.3) will generate the following endpoints:
- Python: /math.Math/powerOfTwo
- Java: /math.Math/powerOfTwo
- C++: /::math.Math/powerOfTwo

```
package math;

struct Request
{
    int16 value;
};

struct Response
{
    uint32 value;
};

service Math
{
    rpc Response powerOfTwo(Request);
};
```

Code:
- https://github.com/ndsev/zserio/blob/master/compiler/extensions/cpp/freemarker/Service.cpp.ftl#L22
- https://github.com/ndsev/zserio/blob/master/compiler/extensions/java/freemarker/Service.java.ftl#L54
- https://github.com/ndsev/zserio/blob/master/compiler/extensions/python/freemarker/Service.py.ftl#L6

**Comment by mikir** [comment]
OK. Thanks for pointing this out! We will fix it.

**Comment by Mi-La** [comment]
Fixed by https://github.com/ndsev/zserio/commit/f03e86f696ce41204ecb4b1f15390736541ab1a8
