### ISSUE TITLE
Python: Zserio PIP package is available

### ISSUE THREAD

**Issue by josephbirkner** [ndsev/zserio#196]
Zserio could make use of the Python package delivery mechanism: The Python Package Index (PyPI)! There are at least three use-cases for a `zserio` pip package:
1. Runtime delivery: The zserio pip package only provides the Python runtime. Separate download of zserio.jar would be necessary.
2. JAR delivery: The `zserio` package could also include `zserio.jar` and provide abstractions to call it (a.k.a `zswag.package()` here: https://github.com/Klebert-Engineering/zswag#importing-zserio-package-sources).
3. Command delivery: The python package could expose the `zserio` command, and with it the zserio.jar command line interface. This would make `pip install zserio` useful for all zserio users, not just python package devs. After installation, you could call `zserio -cpp mystruct.zs`.

**Comment by MisterGC** [comment]
Currently zserio is only  released on GitHub but it would be good to also have PyPi packages available with each release. There is now also https://github.com/Klebert-Engineering/zserio-version-manager which is a good starting point for automated PyPi releases.

**Comment by mikir** [comment]
Zserio PyPi package has been implemented in a brand new repository: https://github.com/ndsev/zserio-pypi
