### ISSUE TITLE
Cross language portability for array size

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#200]
Currently, there are no limitation for array size in the zserio schema. This can lead to the schema generating code which behaves differently in different generators.

Example:

```
struct NotPortableArraySize
{
    varuint64 numEntries;
    uint8     someArray[numEntries];
};
```

The problem is that some languages have limitation for array size due to used underlying native type for indexing:

**Java:** 32 signed bits is used for indexing. Hence, `numEntries` cannot be bigger than 2^31-1.
**32-bits C++**: 32 unsigned bits is used for indexing. Hence, `numEntries` cannot be  bigger than 2^32-1.

It seems that we should introduce some restriction for array size in zserio which will fulfill Java restriction. Because of that, we suggest to introduce new zserio variable integer type **`varsize`** which can hold 31-bits unsigned integer value (min = 0, max = 2^31-1 = 2 147 483 647). It will have the following internal layout:

 	[byte 1]: 1 bit has next byte, 7 (3) bits value
	[byte 2]: 1 bit has next byte, 7 bits value
	[byte 3]: 1 bit has next byte, 7 bits value
	[byte 4]: 1 bit has next byte, 7 bits value
	[byte 5]: 8 bits value

This `varsize` type will be used for auto arrays and can be used for the schema as well:

```
struct PortableArraySize
{
    varsize numEntries;
    uint8   someArray[numEntries];
};
```

If user will use bigger type for array size (not recommended, wrong schema coding style):

```
struct ArraySize
{
    uint64  numEntries;
    uint8   someArray[numEntries];
};
```

the generated code in all languages (which support bigger arrays) will refuse to write array with length bigger than (2^31 - 1) elements. Hence, (2^31 - 1) limitation will be valid for all arrays for all generators to fullfil cross language portability.

**Comment by dirkonet** [comment]
It looks like some JVM implementations have an upper array size limit of even fewer than 2³¹-1 entries. See [this StackOverflow answer](https://stackoverflow.com/a/8381338) with some references to the OpenJDK source code regarding ArrayList and [this StackOverflow answer](https://stackoverflow.com/a/31388054) regarding native arrays. 
Integer.MAX_VALUE in Java is 2³¹-1, maximum array size seems to be somewhere between 2³¹-9 and 2³¹-1 depending on the JVM.

**Comment by mikir** [comment]
Thank you to point this out!

**Comment by mikir** [comment]
There was created a special issue #213 for JVM implementation issue.
