### ISSUE TITLE
Functions return compound by value in C++

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#219]
The C++ generated code returns compound by value in functions. This can lead to extra memory allocation when such functions are called. Example:

```
struct Holder
{
    uint32 offsets[];
};

struct Test
{
    Holder holder;

    function Holder getHolderField()
    {
        return holder;
    }
};
```

Because of that, functions should return compound by constant reference in C++.

**Update:**
Since we have merged ASIL to github, this became almost obsolete.
However constant reference is not enough for compound types and we should generate also non-const version of functions returning compound types. This is needed e.g. for introspectable feature - see #103.

**Comment by Mi-La** [comment]
Currently we decided to generate all functions returning non-simple types in both const and non-const versions.
Note that for functions returning string we generate single function returning StringView when the result expression is a constant string.
