### ISSUE TITLE
GenerateZSerioAPI invokes the zserio compiler with every incremental build

### ISSUE THREAD

**Issue by reinco** [ndsev/zserio#231]
GenerateZSerioAPI()  (in ZSerio_utils.cmake)  uses execute_process() to call the zserio compiler. The problem is with incremental builds. In that case the zserio compiler is called in every incremental build, resulting in recompilation of code that did not change.

potential solution: let the GenerateZSerioAPI  make a custom target (with a name based upon arguments to GenerateZSerioAPI )

**Comment by mikir** [comment]
Not sure if I understand the request correctly. Currently, zserio_utils.cmake already uses custom target for generation sources using zserio. Could you please give us more details?

**Comment by mikir** [comment]
Please reopen it if it's still relevant.
