### ISSUE TITLE
Python: Consider to use keyword arguments

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#234]
Consider to generate keyword arguments for the method 'fromFields' in Python. If some reasonable defaults are provided, this will help users to use more complicated structures.

Consider to join empty constructor and 'fromFields' method into one constructor.

**Comment by mikir** [comment]
Please investigate the possibility of removal `None` defaults for enumeration types, bitmask types, compound types and extern types. This will allow to remove `None` alternative from type annotation `typing.Union[type, None]`.

Builtin types `int`, `float`, `str` and `bool` have already default set to `0`, `0.0`, `""` and `False`.

Array types have already default set to empty `List`.

Optional fields will have always default set to `None`.

**Comment by mikir** [comment]
> Please investigate the possibility of removal `None` defaults for enumeration types, bitmask types, compound types and extern types. This will allow to remove `None` alternative from type annotation `typing.Union[type, None]`.
> 
> Builtin types `int`, `float`, `str` and `bool` have already default set to `0`, `0.0`, `""` and `False`.
> 
> Array types have already default set to empty `List`.
> 
> Optional fields will have always default set to `None`.

This solution will lead to recursive default initialization of whole tree. Such feature is not needed for now. The same behavior is in Java (no recursive default initialization).

**Comment by Mi-La** [comment]
It seem that type annotations for structure members (see #238) are not needed at all when all fields are passed in constructor.
