### ISSUE TITLE
Emitted  python code for fromFields method is incorrect in case of an optional array

### ISSUE THREAD

**Issue by reinco** [ndsev/zserio#240]
Example:
`struct LocationPath
{
...
 optional RoadType roadProperties[];
...
};`

emits:
`class LocationPath():
    def fromFields(..., roadProperties_,...):
       ...
        instance.setRoadProperties(roadProperties_)
        ...
        return instance

   def setRoadProperties(self, roadProperties_):
        self._roadProperties_ = zserio.array.Array(zserio.array.ObjectArrayTraits(self._elementCreator_roadProperties), roadProperties_, isAuto=True)`

The problem is when trying to fill the optional array to non present (so None).
The function setRoadProperties() does not verify that None is passed.
As a result it becomes impossible to use the fromFields() method to instantiate the members of the class in case one does not which to fill the roadProperties array.

The only workaround: instantiate an new instance of LocationPath(). Then call all setXXX() methods individually except setRoadProperties().

**Comment by mikir** [comment]
Thank you very much to point this out! You are right. We will fix it in the current sprint.
