### ISSUE TITLE
Markdown documentation comment doesn't work when indented

### ISSUE THREAD

**Issue by Mi-La** [ndsev/zserio#249]
```
struct TestStruct
{
    /*!
    # This is indented markdown.
       * bullet1
       * bullet2
   
    column1 | column2
    ----------- | -----------
    table       | doesn't work
    !*/
    uint32 field;
};
```
Markdown converter doesn't convert bullets, tables, images, etc. correctly since the markdown comes to it indented.

**Comment by Mi-La** [comment]
Implemented with a simple "heuristic":
First line defines the indentation of the whole markdown. If and only if all other lines starts with the exactly same indentation (or is empty), the indentation is stripped from each line. Otherwise the markdown is left untouched.

**Comment by mikir** [comment]
We should check markdown comment indentation according to the first line which contains `/*!`.
