### ISSUE TITLE
Python: Service Client Implementation Registry

### ISSUE THREAD

**Issue by josephbirkner** [ndsev/zserio#263]
Currently, it is necessary to always provide an instance of a service client implementation to the constructor of a service. This interface is a bit cumbersome to use, since it requires the developer to always become intimate with a service implementation when they want to use a service. An alternative interface should be considered, where all a developer has to do is to pass a (URL-)string into a service. For example:

```python
from my.package.service import Service
client = Service.Client("http://my-rest-service-server:8080")
``` 

In this example, a REST-based service client should be instantiated in the background. The zserio runtime would need to provide a registry that can be used to register certain (url-pattern, impl-factory) pairs. For example:

```python
from zserio.service import ServiceInterface, ServiceInterfaceRegistry

class RESTService(ServiceInterface)
    ... # REST Service client implementation

ServiceInterfaceRegistry.insert("http://.*", RESTService)
```

In this case, the call to ServiceInterfaceRegistry.insert would enable the toy example above.

The signature of the insert-function would be something like
```python
def insert(url_regex: str, factory: Callable[[str], ServiceInterface]):
    ...
```

Such a scheme would enable hiding service implementation details from developers. Note: This is of particular interest for the Python runtime, where a singleton registry global variable is not a problem. In C++ on the other hand, it would probably not work due to the static linking of the zserio runtime. I am not sure about Java.

**Comment by josephbirkner** [comment]
I would suggest to close this issue, since our users seem to be happy with the current interface 😃

**Comment by mikir** [comment]
Perfect. :-) Thanks for note!
