### ISSUE TITLE
[C++] Constructor parameters should not be by-value exclusively

### ISSUE THREAD

**Issue by frank-aurich** [ndsev/zserio#270]
For each zserio object that holds other complex types as members, the C++ generator produces a templated constructor where all the complex types must be provided as r-values.
```
struct Position
{
  int x;
  int y;
}
struct Line
{
    Position p1;
    Position p2;
}
```
The above zserio script will produce a `Line` constructor:
```c++
template <typename ZSERIO_T_p1, typename ZSERIO_T_p2>
explicit Line(ZSERIO_T_p0&& p1_, ZSERIO_T_p0&& p2_)
[...]    
```
Both members must be provided as r-values, otherwise it will not compile:
```c++
Position p1(162791424, 609027496);
Position p2(164375912, 608563336);
Line line(p1, p2);  // does not compile
Line line(std::move(p1), std::move(p2));  // does not compile either
Line line(Position(0,0), Position(1,1));  // works
```

### Proposal
Make the parameters by-value, so that the caller has the option to provide r- or l-values.

**Comment by Mi-La** [comment]
Hi. Please note that those parameters are not always r-values. It's called Universal References in C++11 and both r-value and l-value can be passed. Do you compile it with C++11 enabled?

**Comment by frank-aurich** [comment]
Actually I'm compiling with C++14 enabled.

I use Visual Studio 2017, and the compiler flag `/std:c++14` is set.

**Comment by mikir** [comment]
Hmmm, strange. It works here for gcc 9.3.0 (linux). Could you please put it here a compilation error message from the unsuccessful attempt using `Line line(p1, p2);`? Thanks.

**Comment by frank-aurich** [comment]
You're right, it works as expected.  
The example above is incomplete, as it does not actually produce the described behavior.

If we change the code to this:
```
struct Position
{
  int32 x;
  int32 y;
};

struct Line
{
    Position p1;
    varsize numPositions;
    Position pn[numPositions];
};
```

then in generated C++ code, the following line does not compile:
```c++
Line line(Position{20, 40}, 1, { Position{30,70} });
```
The error message (and Intellisense of Visual Studio) are misleading here, as both blame the first parameter of the call as wrong, while in fact it is the last one. Apparently the compiler can't deduce that the last parameter ought to be a `vector`.

Changing the line to this works fine:
```c++
Line line(Position{20, 40}, 1, std::vector<Position>{ Position{30,70} });
```
