### ISSUE TITLE
Default package is compiled with directory specified on command line

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#273]
Default package cannot have any package specification. However, if the compilation of default package is invoked by the command line with package specification (with directory), it works. Example of source `default_package.zs`:

```
struct StructureInDefaultPackage
{
    uint32 value;
}; 
```

Command line:

```
java -jar zserio.jar path/default_package.zs
```

Such compilation of default packages should be disabled and reported as an error.

**Comment by Mi-La** [comment]
The correct compilation command which will remain allowed is:
```
java -jar zserio.jar -src path default_package.zs
```
