### ISSUE TITLE
Python: Consider to simplify calling of write and read methods

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#277]
Currently, serialization or deserialization of generated object is not possible to provide by single command. For example:

```
writer = zserio.BitstreamWriter()  
obj.write(writer)  
writer.getByteArray()
```
However, it will be more convenient for users to provide the same functionality by single command. Example:

```
zserio.serialize(obj)
```

**Comment by josephbirkner** [comment]
Why not `obj.serialize()`?

**Comment by Mi-La** [comment]
Since `serialize` will implement very common logic, which is the same for all objects, and we already have `write` method on generated objects, we somehow feel that it's better to have it just as an utility. Why to provide two methods on the "API" which do the same logic? User then doesn't know which one should be used.

**Comment by mikir** [comment]
Serialization to the buffer does not have to be byte aligned (divisible by 8) and it's possible that not all bits of the last byte are used. In this case, only most significant bits of the corresponding size are used. Because of that, we are using `BitBuffer` for `serialization` and `deserialization` methods:

```
def serialize(obj: typing.Any) -> BitBuffer:
def deserialize(objClass: typing.Type[typing.Any], bitBuffer: BitBuffer, *args) -> typing.Any:
```

For users which do not need exact number of bits to which the given object will be serialized, there will be another methods:

```
def serializeToBytes(obj: typing.Any) -> bytes:
def deserializeBytes(objClass: typing.Type[typing.Any], buffer: bytes, *args) -> typing.Any:
```

However, the `deserializeBytes` method can potentially use all bits of the last byte even if not all of them were written during serialization (because there is no way how to specify exact number of bits). Thus, it could allow reading behind stream (possibly in case of damaged data).
