### ISSUE TITLE
Rename indicators

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#284]
Indicators are `has` methods which are generated for optional members. Indicator returns `true` only if optional condition of member is satisfied.

However, this can be misinterpreted by users that indicator returns `true` only if optional member is set.

Beside of that, it is easy to introduce clashing with indicators if properties are generated in Python (see #233). For example:

```
struct ClashWithProperties
{
    bool hasValue; // generates property hasValue
    uint32 value if hasValue; // generates property value and indicator hasValue => clash
};
```

We should consider to rename indicator `hasValue` to e.g. `evaluateValueOptionalCondition`. Such longer name will be more descriptive and more intuitive for users and it will prevent such easy clashes as described by previous example.

**Comment by mikir** [comment]
Some other examples of naming: `isValueConditionTrue`, `conditionValueIsMet` or something similar to express that it returns true or false.

**Comment by mikir** [comment]
Yet another example: `isValueOptionalClauseMet`.

**Comment by Mi-La** [comment]
The new naming would be misleading for auto optional field. At the end we will introduce two new forms of indicator method:
   1. For optional field `someField` with an if clause:
      * `isSomeFieldOptionalClauseMet`
   1. For **auto** optional field `someField`:
      * `isSomeFieldSet`

**Comment by MisterGC** [comment]
What about using  `requires/uses/expectsMember/Field<FieldName>` - to express the semantic meaning of using a optional member/field condition?

**Comment by Mi-La** [comment]
This would be usable for optional fields which have the "optional if clause" - i.e.  classic non-auto optionals. But for auto optionals (where `optional` keyword is used) it doesn't make sense.
And also the `requires` and `expects` seems to express the meaning only for users of writing part of the interface. I know that proposed `is${field}OptionalClauseMet` is quite long and ugly, but it express exactly what it does and yet it prevents easy clashes :-).
Indicator `is${field}Set` for **auto** optionals seems quite ok for me.

**Comment by Mi-La** [comment]
In any case thanks for sharing the ideas. Feel free to share more if you think up yet anything else. I have almost finished this task, but if we find-out some better naming, I've no problem to change it. The biggest problem in this issue is to find the proper naming ;-).

**Comment by Mi-La** [comment]
What about `isSomeFieldUsed` or maybe yet better `isSomeFieldPresent`? This would express that the field is used/present or not in the serialized bit stream.

**Comment by mikir** [comment]
We will use `is<FieldName>FieldUsed` for now.

**Comment by mikir** [comment]
`Field` in the suffix seems to be redundant because setters and getters do not use such suffix as well. Moreover, if the name of the field is for example `myGreatField`, the result is `isMyGreatFieldFieldUsed`.
