### ISSUE TITLE
Python: Consider to use different naming convention

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#285]
Currently, the generated Python sources use the following naming convention which are directly inspired by naming convention in schemas:

Directory names (packages): `lower_case_with_underscores`
File names: `CapitalizedWords`
Class names: `CapitalizedWords`
Class methods and properties: `mixedCase`
Class members and variables: `mixedCase`

Such convention helps users to match generated Python sources directly to the Zserio schemas.

However, this naming convention can be inconvenient for Python users (please see https://www.python.org/dev/peps/pep-0008/#naming-conventions). 

This issue is about to open discussion for Python users if it is worth to change naming convention of generated Python sources. 

Please note, that if we change the naming convention, we should solve possible clashing as well. For example, if class methods and properties should use `lower_case_with_underscores` naming convention, we should solve somehow the following possible clashing:

```
struct PythonPropertyClashExample
{
    uint32 myField;  // generates property 'my_field'
    uint32 my_field; // generates property 'my_field' as well -> clash 
};
```

**Comment by josephbirkner** [comment]
I don't think the clashing case is very likely, but if one occurs, you could skip the snake case conversion for that symbol while outputting a warning. As a Python developer, it I would find it **amazing** if zserio would output pythonic identifiers!

**Comment by Mi-La** [comment]
I understand that you would like it :-). It's even possible to do. But from the past we already know that clashes are not so unlikely. It means that it would be really necessary to implement some checking. The main benefit of the current solution is that **we don't need the checking at all** (except `-withPythonProperties` - see #233). At first we should consider if it's worth to spend resources on implementing such feature just because it would be nice.

Also note that the check would have been done only in Python generator. So if a user will design a schema and test it in other languages, the he will have problems once switching to Python. Firing the warning from Zserio core (i.e. also when compiling C++ or rendering HTML documentation) probably also isn't good idea.

**Comment by Mi-La** [comment]
There would be also another subtle problems:
```
struct SomeStruct
{
    uint32 someField; // first one, we will name it 'some_field' in Python
    uint32 some_field; // some_field is used, so how to rename? some_field_2?
    uint32 some_Field; // some_field is used, so how to rename? some_field_3 or some_Field?
};
```
We would need to define some extra logic how to assign names to the fields in generated code.

**Comment by MisterGC** [comment]
For flexibility- and backwards-compatibility reasons I suggest to introduce a `-apiStyle` param which could be either `PEP8` (=default) or `ZserioCommon` - Regarding the potential clashes, zserio should imo not try to fix the issues but just report them and schema authors have to find a workaround

**Comment by mikir** [comment]
PEP8 tells:

Directory names (packages): `lower_case_with_underscores`
File names (modules): `lower_case_with_underscores`
Class names: `CapitalizedWords`
Class methods and properties: `lower_case_with_underscores`
Class members and variables: `lower_case_with_underscores`

**Comment by mikir** [comment]
> Aside from the PEP-8 clash, the latter just feels very redundant, and occasionally I forget that I have to import the nested Symbol and obviously get very weird errors. Let me know if I should create a separate ticket for this. Thanks!

Yes, please create a separate ticket to this. We will continue with discussion about this separately.

**Comment by mikir** [comment]
We did some deep investigation of this issue and unfortunately, we are not able to find out any quick solution for this issue and the effort could be a problem.

We have identified five steps which shall be done:

- We should adapt runtime library to comply PEP-8.
- We should implement PEP-8 in Python API together with current API.
- We should implement checking of possible clashing in new PEP-8 API.
- We should implement case checking (#66) to avoid clashes introduced only by different case. This will solve some obscure problems on Windows as well.
- We should adapt our test framework to check properly both generated API(s). This will take weeks because currently we have 1188 tests.

We suggest also to generate properties only together with new naming convention (PEP-8). This will give us only one generated API which can fail because of clashing.

We suggest as well not to generate PEP-8 by default because it can be easily broken (properties, underscores). Unfortunately, clashes are not so obvious but it really matters. For example:

`const GEOMETRY_VALUE` and `struct GeometryValue`

We think this won't be obvious for schema editors that this is no-go for Python PEP-8. Sooner or later somebody will use it. And this is only one example how to introduce PEP-8 clash.

It would look really weird if our Python generator will fail to generate API from valid zserio source by default. Users will be surprised and they will complain about such behavior for sure.

**Comment by josephbirkner** [comment]
Related: https://github.com/ndsev/zserio-pypi/issues/2

**Comment by josephbirkner** [comment]
@mikir A small note: In your example above, why are `const GEOMETRY_VALUE` and `struct GeometryValue` clashing? UPPER_CASE_WITH_UNDERSCORES is the constant style required by PEP-8.

**Comment by mikir** [comment]
The problem is the clashing of generated file names (Python modules) on the file system. Constants and types are generated in separated files. Constant `const GEOMETRY_VALUE` will be generated to the file `geometry_value.py` (PEP-8 module name convention) and `struct GeometryValue` will be generated to the same file `geometry_value.py` (again PEP-8 module name convention).

Unfortunately, it's no so easy to detect all such clashes. We have quite problem to realize what can happen if one start to rename package keywords. 

Our current solution does not rename any keyword in the package (GEOMETRY_VALUE.py and GeometryValue.py), so there is no clash thanks the uniqueness of symbols in the package.

**Comment by josephbirkner** [comment]
Then maybe for this ticket you can skip PEP-8 alignment for module names until you deal with #289 ?

**Comment by mikir** [comment]
Yep, this particular problem can be solved by some prefix which cannot be used by any package keyword. We will have to identify all such problems somehow and to find out workarounds for them not to break generated code. It will take.

Regarding #289, `package.api` is already implemented as `api.py`.

**Comment by Mi-La** [comment]
We going to generated properties and functions to be PEP-8 compliant. We use use simple logic to rename symbols coming from Zserio script. We will add `_` before each uppercase letter if there is either a number of a lowercase letter before it. Then we just convert the new symbol to lowercase. See following examples.
```
myField -> my_field
field1Array -> field1_array
testABC -> test_abc
test_XYZ -> test_xyz
```

What about names of generated classes? Should we remove underscores if they are used in e.g. structure name?
```
struct This_Is_My_Strucuture
{
    // ...
};
```
We can easily generate module `this_is_my_structure.py`, but what about the class name? Does it make sense to try to get `ThisIsMyStructure`?

**Comment by Mi-La** [comment]
And what about enum items and bitmask values? Should we rename input from Zserio to correct PEP-8 naming?
```
enum TestEnum
{
    itemOne,
    itemTwo,
    itemThree
};
```
Currenlty it will produce `itemOne`, `itemTwo`, `itemThree` in generated Python code, but it should be: `ITEM_ONE`, `ITEM_TWO`, `ITEM_THREE` according to the PEP-8.

**Comment by mikir** [comment]
We will change renaming from camel case to snake case not to insert any underscores after numbers. The number can be already considered to be a visual separator. 

Examples:

```
Line2D -> line2d // not line2_d
Some3DBuffer -> some3dbuffer // not some3_dbuffer
```

But this could be a little bit misleading for the following example:

```
package fts3_virtual_table;

sql_table Fts3VirtualTable using fts3
{
    string      title;
    string      body;
};
```

This will create package `fts3_virtual_table` but module will be named `fts3virtual_table`.

Unfortunately, we cannot see any better generic solution for such renaming. It seems there will be always some examples which will be not very intuitive.

**Comment by Mi-La** [comment]
At the end we have improved the renaming logic little bit. Now we add the underscore also before the last uppercase letter in uppercase sequences. The improvement also covers cases where there is a number in the name.
Examples:
```
Fts3VirtualTable -> fts3_virtual_table
Vector2D -> vector2d
Vector2DPosition -> vector2d_position
```
Basically we use the following regex replace: `([0-9A-Z])([A-Z][a-z])` -> `$1_$2` in addition to the basic camel case regex replace: `([a-z])([A-Z])` -> `$1_$2`.
