### ISSUE TITLE
Add functions to use bitmasks in a more natural way

### ISSUE THREAD

**Issue by reinco** [ndsev/zserio#291]
Is it possible to make the generated code for zserio type bitmask somewhat smarter?
Since it is a bitmask, I was expecting some bitmask related functions.
For example: how to populate a bitmask with multiple enum values? Now I have to use the underlying data type (uint32_t) to build up the mask. That is just ugly. There should be no need to expose the underlying datatype in the interface.

Concretely add some generated functions similar like the following:
1. void add(Values value); // add 1 enum value
2. void add(const std::vector<Values>& values); // add many values
3. bool hasValue(Values value) const; // returns true if the bitmask includes the given value
4. void remove(Values value); // remove a value from the bitmask
5. void clear(); // reset bitmask to empty
6. bool empty() const; // returns true if no element is set in the mask

And maybe also add some more advanced functions that take advantage of the underlying int datatype for efficiently testing for multiple values:
5. bool hasAllOf(const std::vector<Values>& values); // returns true if all given values are part of the set
6. template<typename... Args> bool hasAllOf(Values value, Args... args); // templated version of hasAllOf, such that one can test, fruitBasket.hasAllOf(Apple, Banana)
7. bool hasAnyOf(const std::vector<Values>& values); // returns true if any value of given values are part of the set
8. template<typename... Args> bool hasAnyOf(Values value, Args... args); // templated version of hasAnyOf, such that one can test, fruitBasket.hasAnyOf(Apple, Banana)
9. template<typename... Args> add(Values value, Args... args); // add many values

An alternative is to adding such functions to every class generated for a bitmask, is to generate one bitmask.h with templated functions to achieve the same goal.

**Comment by reinco** [comment]
I now saw there are functions, but defined below the generated class whereas I was looking in the class definition itself, which was somewhat surprising to me. They can be used to accomplish the thing I want.
Probably no change is needed then in the zserio emitter, but I leave that decision to you.

**Comment by mikir** [comment]
As far as I remember the main reason for that was implicit conversion of `lhs` argument. If you implement these operators as members, the implicit conversion of `lhs` argument won't be possible.
