### ISSUE TITLE
Python: Symbol and top level package name clash

### ISSUE THREAD

**Issue by Mi-La** [ndsev/zserio#293]
Currently we use fully qualified names for specifying entities in generated code to prevent ambiguities. However even the fully qualified names can cause problems. The problem occurs when a symbol, either a local variable, argument or even a function or **property** has the same name as the top level package. See following situations:

**Properties:**
Input:
```
package top_level.some.pkg;

struct Test
{
    uint32 top_level;
};
```

Generated:
```
    @property
    def top_level(self) -> typing.Union[top_level.some.pkg.Test, None]: # so far this is ok
        return self._top_level;

    # In the setter definition, the top_level identifier in `typing.Union[top_level.some.pkg.Test]` is resolved
    # as the property top_level which was just defined above and thus the code fails with an error:
    # 'top_level' property does not have attribue 'some'
    @top_level.setter
    def top_level(self, top_level_ : typing.Union[top_level.some.pkg.Test, None]) -> None:
        self._top_level = top_level_;
```

The situation would be similar if the property was named "typing", which would clash with imported typing module.

**Comment by Mi-La** [comment]
We have another example with a method argument, e.g. for generated `read` method. This will occur when the top level package is named `reader` and the current compound have some `Other` compound as a child.

Generated:
```
    def read(self, reader : zserio.BitStreamReader) -> None:
        # here the reader is resolved as the reader argument and we cannot get to the Other compound
        self._other = reader.pkg.Other.fromReader(reader)
```

**Comment by Mi-La** [comment]
**Workaround:**
Even though we are not able to detect these clashes right know, there is already a workaround by using `-setTopLevelPackage` command line option, which will add an extra top level package with choosen name.

**Comment by Mi-La** [comment]
At first we will use:
```
from __future__ import annotations
```
It will prevent Python from error while processing typing annotations which clash with a top level package. Mypy will still complain, but at least the code will be usable.

**Comment by Mi-La** [comment]
Note that we are not able to catch all possible clashes, since Python contain lot of various modules and packages and we cannot know which packages are used by the user. Moreover, some of the modules are already present in `sys.modules` just after Python startup and it's not possible to import our generated packages which have the same name as any of the "implicitly imported pacakges". This seems to be undocumented feature of Python and the list of packages which are in `sys.modules` can probably vary between Python versions / implementations. To check which packages are imported after the startup run:
```
import sys
sys.modules.keys()
```
We only disallowed `typing` since we use the `typing` module in generated code. Other issues must be solved by users, the easiest solution is to use `-setTopLevelOption` to set some "safe" name.

**Comment by Mi-La** [comment]
Consider if importing `typing` in zserio `__int__.py` could help.

**Comment by mikir** [comment]
> Consider if importing `typing` in zserio `__int__.py` could help.

No action needed at the moment. We just put a note regarding this possibility to the sources.
