### ISSUE TITLE
Python: Package named 'api' breaks generated api.py helpers

### ISSUE THREAD

**Issue by Mi-La** [ndsev/zserio#295]
When some package is named 'api', the folder `api` will occur in the tree of generated code. We will get something like this (e.g. for `test/api.zs` and defined structure `Test`):

```
.
+-- test
|   +-- api
|   |   +-- Test.py
|   +-- api.py
```
Now it's very complicated to import the `api.py` since the `api` package is preferred by Python import logic. Moreover when the `api` package is somewhere in the middle of more complicated schema, it will break importing of the generated `api` helpers since they unintentionally import `api` packages instead of the `api.py` modules.

**Comment by Mi-La** [comment]
We should investigate if it's possible to do some hand-made imports easily in Python 3. The we could do all modules imports manually by some custom `import_module` function and thus prevent possible clashing of modules and packages imports.

**Comment by josephbirkner** [comment]
Perhaps related to #289 ?

**Comment by Mi-La** [comment]
Will be forbidden with a special check for now.
