### ISSUE TITLE
zserio --help - provides instruction with 'java -jar ...' but it should use the zserio command.

### ISSUE THREAD

**Issue by MisterGC** [ndsev/zserio#301]
When using the pip package and typing `zserio --help`, users still get `Usage: java -jar zserio.jar <options> zserioInputFile` but this is confusing and doesn't encourage people to keep on using the `zserio` command.

**Comment by mikir** [comment]
Currently, zserio jar compiler does not know if it has been invoked by python command line.

We will investigate how this invocation can be easily detected. Then, we could improve the help message.

**Comment by mikir** [comment]
Fixed. Now python command line will print help with `Usage: zserio <options>`.
