### ISSUE TITLE
Do not append _method in generated service clients

### ISSUE THREAD

**Issue by josephbirkner** [ndsev/zserio#303]
Zserio appends `*_method`/`*Method` suffixes to generated service Client APIs. I understand that this was done to prevent clashes, but at the same time it bloats the code a bit and users have to learn about it. A suffix like this also does not exist for struct fields - so it would be nice if service methods could just have their names from the schema...

**Comment by Mi-La** [comment]
You mean the names from schema converted to snake case (PEP-8) I suppose (which users also have to learn ;-)).

**Comment by mikir** [comment]
Yes, we can improve it. We can check explicitly clashes and report error similarly as was done for struct fields. This will allow us to remove `_method` suffixes from generated service Client APIs.
