### ISSUE TITLE
Add support for code documentation

### ISSUE THREAD

**Issue by PeachOS** [ndsev/zserio#32]
I would like to document my zserio code so that the documentation also appears in the generated code. In the end I want to be able to generate a documentation (of the generated code!) with Doxygen or Javadoc respectively.

Something like the following should be properly considered by the emitter:

```
/*
 * @brief Experience instance
 * @since 0.1.0
 */
struct Experience
{
    bit:6       yearsOfExperience;
    Language    programmingLanguage;
};

/*
 * @brief Programming language enum
 * @since 0.2.0
 */
enum bit:2 Language
{
    CPP     = 0,
    JAVA    = 1,
    PYTHON  = 2,
    JS      = 3
};
```

**Comment by mikir** [comment]
Thank you very  much for your post. We like this idea because it will increase the readability of generated code. Because we are busy with grpc just now, we will put this to the backlog but we will keep in mind this for the future releases.

**Comment by mikir** [comment]
We have implemented documentation comments in the generated code using new command line argument `-withCodeComments`.
Documentaion comments in the generated code are disabled by default (`-withoutCodeComments`).
