### ISSUE TITLE
Add types schema info in generated Python code

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#329]
Currently, no schema info is available in generated Python code.

It would be nice to introduce new command line option like `-withTypeInfoCode` which will cause to generate schema info for all generated types (preferably it should be a static method).

Generated schema info should contain available schema information for types like original names in schema, fully qualified type names, if the member is optional, if the member is implicit array, etc...

Generated schema info could contain as well a reference to the corresponded Python object, e.g. for compound member.

Consider to implement support for schema info in Python runtime (e.g. classes `TypeInfo` or `MemberInfo`) which will be used by generated code.

**Comment by Mi-La** [comment]
We have introduced new `typeinfo` module in Zserio Python runtime, and we generate
```
@staticmethod
def type_info() -> zserio.typeinfo.TypeInfo():
    ...
```
for each generated user type (except `subtype` and `instantiate`).

Within a `TypeInfo` object, schema info about the of the whole sub-tree is available. To keep the `*Info` classes simple and generic, they provide schema related information using attributes approach - i.e. most of the schema info is stored in a dictionary, where the key is an `*Attribute` enumeration and the value is of `typing.Any` type which depends on the key.

Example:
```
type_info = TestStructure.type_info()
fields = type_info.attributes[zserio.typeinfo.TypeAttribute.FIELDS]
firstField = fields[0] # zserio.typeinfo.MemberInfo of the first field
print(firstField.schemaName) # name of the first field as is defined in the Zserio schema
print(firstField.attributes[zserio.typeinfo.MemberAttribute.PROPERTY_NAME]) # property name generated in the Python code
if zserio.typeinfo.MemberAttribute.OPTIONAL in firstField.attributes:
    print("first field is optional")
```
