### ISSUE TITLE
add_zserio_module cmake function

### ISSUE THREAD

**Issue by MisterGC** [ndsev/zserio#333]
Consider adopting the add_zserio_module cmake function: https://github.com/Klebert-Engineering/zsr/blob/ab996287d753745a97e7b354ab0ddd9f724e79bd/runtime/CMakeLists.txt#L223

**Comment by mikir** [comment]
Currently, we uses `zserio_add_library` cmake function which we need for our test framework. It might be interesting to investigate provided `add_zserio_module` function from user application to gather new ideas or improvements.

**Comment by josephbirkner** [comment]
I think that `zserio_add_library` will actually work fine! We will investigate and report back.

**Comment by josephbirkner** [comment]
After looking into it a bit more the existing function did not work out for us because it does not support globbing. We added the functionality we need in this repo: https://github.com/Klebert-Engineering/zserio-cmake-helper

**Comment by mikir** [comment]
Thanks for your note and for your link.

We don't use globbing intentionally to be able to check if all expected sources are generated correctly in our test framework. For us, it would be probably better to generate `CMakeLists.txt` automatically by zserio.

Besides of that, we should invent some official cmake support not to force users to rely on our test framework. We will investigate this further.

**Comment by mikir** [comment]
This issue will be solved in scope of the issue #560.
