### ISSUE TITLE
Add easy way to write a c++ object to a bit stream

### ISSUE THREAD

**Issue by reinco** [ndsev/zserio#338]
Using the new c++ emitter (in 2.4.0-pre2), it has become harder to write an object to a bit stream.
An easier way should be added, because now I have to write a lot of boiler plate code.

So something like the following should still be possible, maybe using a template:
`BitStreamWriter bsw;
myclass.write(bsw);
size_t size = 0;
auto data = bsw.getWriteBuffer(size);`

**Comment by mikir** [comment]
OK. We can extend runtime library for some user convenient functions.

**Comment by reinco** [comment]
My current workaround is the following, to get the same behavior as in the description.

2 side remarks (as discussed in the joint dev standup):
1. myclass.write() will also call initializeChildren(). In order to construct the BasicBitBuffer we need to call bitSizeOf() which requires that initializeChildren() has already been called. So the fact that write() calls initializeChildren() is actually not useful anymore. Probably it is better that all or no function calls initializeChildren() for functions where child objects must have been initialized.
2. I call bbb.getByteSize() in order to get the blob size in bytes, but actually that is bad, because it should not be assumed that myclass.write() would fill up the complete buffer. As discussed probably the result of getBitPosition() should have been translated to the size in bytes.

myclass.initializeChildren();
zserio::BasicBitBuffer bbb(myclass.bitSizeOf());
zserio::BitStreamWriter bsw(bbb);
myclass.write(bsw);
auto size = bbb.getByteSize();
auto data = bbb.getBuffer();

**Comment by mikir** [comment]
Thanks a lot for remarks. We will pay attention on that.

**Comment by mikir** [comment]
> myclass.write() will also call initializeChildren(). In order to construct the BasicBitBuffer we need to call bitSizeOf() which requires that initializeChildren() has already been called. So the fact that write() calls initializeChildren() is actually not useful anymore. Probably it is better that all or no function calls initializeChildren() for functions where child objects must have been initialized.

New issue because of this problem has been created: #342.

**Comment by mikir** [comment]
The zserio C++ runtime has been extended by utilities which are not used by generated code but which could be useful for applications:

1. `FileUtil.h`
It contains `readBufferFromFile()` and `writeBufferToFile()` methods which read/write bit stream buffer to/from file.
1. `SerializeUtil.h`
It contains `serialize()` and `deserialize()` template methods to allow applications easy serialization or deserialization of zserio objects.
