### ISSUE TITLE
Allow periods in rule IDs in rule_group

### ISSUE THREAD

**Issue by knebelm** [ndsev/zserio#339]
Currently, the regular expression for rule IDs only allows letters, numbers, hyphens and underscores. However, in some projects, a period will also be required. 

Example:

```
rule_group
{
/*! 
  Description of rule.
!*/
rule "name.name-012345";
}
```

**Comment by mikir** [comment]
We have decided to allow the period and colon. This will allow definition of rule ID which fully conforms the HTML4 id attribute:

"_ID and NAME tokens must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens ("-"), underscores ("_"), colons (":"), and periods (".")._"
