### ISSUE TITLE
Parameter `-withWriterCode` is not enabled by default for java generator.

### ISSUE THREAD

**Issue by RobertBudzko-TomTom** [ndsev/zserio#349]
Without explicitly stating `withWriterCode` java code generated yielded classes not implemented fully compared to assigned interfaces. Documentation states writer code is enabled by default.

My command was: `-withoutSqlCode -withoutPubsubCode -withSvgDiagrams -withRangeCheckCode -xml ${basedir}/${codegen.sources.dir} -java ${basedir}/${codegen.sources.dir} -doc ${basedir}/${codegen.doc.dir} -src ${basedir}/${codegen.zserio.root} -setTopLevelPackage nds ${codegen.zserio.file}`.

**Comment by mikir** [comment]
We have tried your command with [this schema](https://github.com/ndsev/zserio/blob/master/test/arguments/with_type_info_code/zs/with_type_info_code.zs) and it seems that it works. At least, Java generated classes have writer interface (e.g. `write` method).

The problem won't be probably so straightforward. Could you please check the schema above if it works as expected? Thanks!
