### ISSUE TITLE
HTML: Used-by links for template parameter types are not linking to instantations

### ISSUE THREAD

**Issue by josephbirkner** [ndsev/zserio#361]
Simple Demo (quickly made using new streamlit UI 😃):

```java
package sample;

struct FieldType {
    int32 x;
};

struct Data<T>
{
    T field;
};

instantiate Data<FieldType> TestStructure32;
```

The `Data` used-by correctly shows `TestStructure32`. But for `FieldType`, the used-by section only shows the unrolled template parameterization (`Data<FieldType>`) instead of `TestStructure32`:

![Screenshot 2022-02-01 at 15-13-49 sample documentation](https://user-images.githubusercontent.com/8723581/151984399-1c404b3c-cdc2-4b35-b633-fe4458dacb5c.png)

It would be great if we could get a fix for this in before 2.5, since we are currently integrating used-by info in the NDS.Live developer portal...

**Comment by mikir** [comment]
OK, thanks for that!

This is connected to issue #262. We will investigate if there is some possibility to change it easily.

**Comment by josephbirkner** [comment]
Ok, thanks!
