### ISSUE TITLE
Introduce real optional value indicator in generated code

### ISSUE THREAD

**Issue by Mi-La** [ndsev/zserio#390]
Currently all languages have indicators generated for optional fields. But those indicators only returns whether an optional condition is met and thus whether an optional field is used. But it doesn't state whether an optional field is already set in a zserio object.
It's not problem for "read only" code, but for code which actually creates zserio object it may be very useful to find out whether the optional field is already set or not.
Java and Python both solve this natively (i.e. null / None values). But in C++ we must introduce special indicator and thus we will have two indicators for optional fields:
```
bool isSomeFieldUsed(); // currently generated, states whether the condition says that the field is used
bool isSomeFieldSet(); // the new one, states whether the underlying optional holder has a value
```
We also need this for Reflectable interaface, because it shall return what's actually set within the object and not what is defined by an optional condition.

See also: #284

**Comment by mikir** [comment]
To be consistent, we will add real optional value indicator into generated Java and Python code as well.
