### ISSUE TITLE
Non-deterministic Hash Codes for Enumerations

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#402]
The hash code of an object is not stable when an enumeration is part of it at least in different runs.</p>

Lets say you read a blob for a database in different runs and calculate the hash. It is expected that for the same blob the hash 
should also be the same but its not because when an enumeration is part of the blob the hash code from the enum name is used instead of the value.

Just take the python tutorial from [github](https://github.com/ndsev/zserio-tutorial-python). Print the hash code in the end of the read_employee method:

```
# print out bit size
print("Bit size of employee: ", employee.bitsizeof())
# new code to demonstrate hash issue
print("Hash code", hash(employee))
```

If you now do the following, you will see the problem:

```
python main.py write_joe
python main.py read
...
Bit size of employee:  137
Hash code 1979046667
python main.py read
...
Bit size of employee:  137
Hash code 1336890910
```

The hash codes are not the same. It would be probably better to overwrite the magic hash method in Python and use the value instead.

Very similar issue is in Java, however the hash codes seem to be the same in this small test. Should be investigated deeper.

**Comment by Mi-La** [comment]
In Python, the enun hash code is different in each run.
In Java, the enum hash code seems to be stable across different runs, but it can be different on different JVMs. This can be also confusing in some use-cases and we should calculate enum hash code from the enum value in all languages to get deterministic values on all machines.
