### ISSUE TITLE
Define and document supported tool chains for all target languages

### ISSUE THREAD

**Issue by MisterGC** [ndsev/zserio#406]
Where can I lookup if there is support for my toolchain when using zserio?

**Comment by mikir** [comment]
Added new section Supported Platforms and Supported Compilers and Supported Versions in the main README files of corresponded generators: [C++](https://github.com/ndsev/zserio/blob/master/compiler/extensions/cpp/README.md#supported-platforms), [Java](https://github.com/ndsev/zserio/blob/master/compiler/extensions/java/README.md#supported-java-version) and [Python](https://github.com/ndsev/zserio/blob/master/compiler/extensions/python/README.md#supported-python-version).
