### ISSUE TITLE
Debug string showing codes as numbers instead of names

### ISSUE THREAD

**Issue by dusho** [ndsev/zserio#416]
When using DebugStringUtil to print out content of zserio file, it shows codes as integers e.g.
```
{
    "shift": 3,
    "content": 1,
    "characsRoadRangeMaps": {
        "numMaps": 3,
        "header": {
            "attributeTypeCode": [
                20,
                21,
                22
            ],
 
        "maps": [
            {
                "attributeTypeCode": 20,
                "feature": 58,
```
which is kind of hard to read unless you have some lookup somewhere.
I would expect to have enum/string values there, something like:
```
RoadCharacteristicsLayer: {
    CharacsRoadRangeAttributeMapList: {
        "COORDSHIFT": "3",
        CharacsRoadRangeAttributeMapListHeader: {
            "ATTRIBUTETYPECODE": ["0": "FUNCTIONAL_ROAD_CLASS", , "1": "PRIORITY_ROAD_CLASS", , "2": "ROAD_TYPE", ],
 
"MAPS": [CharacsRoadRangeAttributeMap: {
                "ATTRIBUTETYPECODE": "FUNCTIONAL_ROAD_CLASS",
       "COORDSHIFT": "3",
                "FEATURE": "58",
```
Would it be possible to adjust serializers to get the names of the codes there? Thanks

**Comment by Mi-La** [comment]
Note that for `enum`s this is quite easy since the `enum` can only have value exactly matching to the definition.

If something similar is needed also for `bitmask`s, it would be much more difficult since `bitmask` can have arbitrary value (which can even be completely different from masks defined in the `bitmask`). Currently the bitmask values are stringified to the following form: `"5[ONE | THREE]"`, where `5` is the exact value and the combination of matching masks is in brackets. Thus parsing of the string input for bitmasks would need more logic and we would need to decide which string formats we would accept (`5`, `"5"`, `"5[ONE | THREE]"`, `"ONE"`, `"ONE | THREE"`, ...).

Do we need this also for bitmasks?

**Comment by dusho** [comment]
True. Well yes, it will be definitely helpful to have this for bitmasks as well - if debug string should be human readable form, then names are always better than obscure numbers you have to look up - especially multiple ORed numbers you have to split.
The format can be whatever is easiest to implement as long as there is that name (ONE | THREE, ...)

**Comment by Mi-La** [comment]
One considered solution was to stringify enumerables to JSON as objects, something like:
```
"myEnum" : {
    "value": 0,
    "string": "ONE"
},
"myBitmask": {
    "value": 3,
    "string": "READ | WRITE"
}
```
Such solution would be quite robust, but it would produce lot of data and it would be much more complicated for parsing, and probably also for editing (when the `"value"` and `"string"` wouldn't match).
Thus we have chosen simpler solution - `JsonWriter` supports a configuration options, whether to write enumerables as strings or as numbers. String format is the default. In string format, the following rules are applied:

1. Enums
   * when an exact match with an enumerable item is found, the item name is used - e.g. `"FIRST"`,
   * when no exact match is found, it's an invalid value, the integral value is converted to string and an appropriate comment is included - e.g. `"10 /* no match */"` (note that such item will not be possible to read from the JSON!).

3. Bitmasks
   * when an exact mach with or-ed bitmask values is found, it's used - e.g. `"READ | WRITE"`,
   * when no exact match is found, but some or-ed values match, the integral value is converted to string and the or-ed values are included in a comment - e.g. `"127 /* READ | CREATE */"` (only the number is significant for reading), 
   * when no match is found at all, the integral value is converted to string and an appropriate comment is included - e.g. `"13 /* no match */"`.

In case of enums, the second case with "no match" should never occur, but bitmasks can generally contain any values within their range. But we suppose that in most cases only plain string variants should occur in JSON debug string.
