### ISSUE TITLE
Enums with larger than 32bit base type doesn't work in C++

### ISSUE THREAD

**Issue by Mi-La** [ndsev/zserio#44]
```
enum bit:63 Enum63
{
    ENUM63_VALUE1 = 0
};
```
MSVC doesn't allow base type other than `int` for enums (prior to C++11). Gcc probably chooses the bigger base type based on the highest value in the enum. We should investigate what C99 standard says about enums.

**Comment by mikir** [comment]
New C++11 Emitter uses strongly typed enumeration. Old C++98 Emitter won't be fixed because it is deprecated.
