### ISSUE TITLE
cpp: Throw exception when check statement exists in 'sql_table' structure.

### ISSUE THREAD

**Issue by kancve** [ndsev/zserio#455]
# Test topic

Refer to the definition of SmartLayerMetadaTable (NDS.Live).

The modified definition of the CountryMapTable is as follows:

``` java
sql_table CountryMapTable
{
    /** Refer to the definition of SmartLayerMetadaTable (NDS.Live), just to reproduce the wrong scene.*/
    int32   tileId sql "PRIMARY KEY DEFAULT 0 NOT NULL";
    Tile    tile;

    sql("check tileId = 0");
};
```
The source code differences are as follows:
![difference](https://user-images.githubusercontent.com/29945891/203000640-2693b2ca-d8b0-4a10-8a3e-70c9aab3e935.png)

# Testing environment

* zserio-2.8.0
* sqlite3-3.39.4
* zs file: come from [zserio](https://github.com/ndsev/zserio/tree/master/test/language/sql_databases/zs)
* Source code (cpp) generation command:

``` shell
java -jar zserio.jar -src zs -cpp cpp sql_databases.zs
```

# Debugging

The problem is caused by the addition of ``", check tileId = 0"`` characters.

I don't quite understand the meaning and role of defining this line. Maybe there is something wrong with the way I use it.

![debugging](https://user-images.githubusercontent.com/29945891/203000736-b137a33b-0a16-423c-85f9-7826ed5e9979.png)

More information can be found [here](https://github.com/kancve/zserio-cpp-test).

**Comment by mikir** [comment]
Thank you very much for such detailed description.

The problem is that zserio just passes the SQL command to SQLite without any syntax check. Because used SQL command has wrong syntax, SQLite throws exception.

The correct syntax should be: `sql("check(tileId == 0)");`

**Comment by kancve** [comment]
I see. Thank you very much.
