### ISSUE TITLE
zserio compatibility management and mechanisms

### ISSUE THREAD

**Issue by MisterGC** [ndsev/zserio#456]
zserio currently uses a version format <major>.<minor>.<patch>. However, at the moment, we increment the <major> version only when the schema language changes in a non-backwards compatible way. This approach is not sufficient for our expanding scope and increasing complexity. Therefore, we are contemplating a more stringent versioning policy explicitly addressing the following compatibility dimensions:

1. **Schema Language Compatibility**: Any changes to the schema language, including the removal or deprecation of language elements, must be carefully managed. The new versioning strategy should account for such changes and consider its implications for backward compatibility. 

2. **API Compatibility**: The versioning strategy should address both the runtime compatibility and the compatibility of the APIs that zserio generates. This includes extension APIs, such as those providing custom language support, which are key to interoperability with other software systems. 

4. **Encoding Compatibility**: All data that may not be directly reflected in the schema but is present in the binary encoding needs to be considered. Ensuring such hidden data's compatibility is crucial to avoid runtime issues and unexpected behaviors. 

5. **Toolchains and Target Platforms Compatibility**: As zserio supports different compilers (MSVC versions, etc.), language versions (C++11, Python 3.9, Java 8 or 11, etc.), and dependency management solutions (PyPi, etc.), the versioning strategy needs to indicate clearly the compatibility with these different environments. The strategy should also address issues of ABI compatibility.

6. **Cross-Language Compatibility**: The versioning strategy must specify the level of interoperability between different language APIs (e.g., Java, C++). This includes guarantees that a data blob written using one language's API can be accurately read by another language's API. Any limitations or incompatibilities across languages must be explicitly documented in the versioning strategy to guide users in multi-language environments. 

7. **(Compatibility with) Dependencies**: Provide an easy way to get a complete list of all dependencies (and versions).

8. **Configuration Compatibility**: Any configuration files or parameters (for example, compiler options) zserio uses, should also be tracked. This includes deprecation or addition of parameters, changes to default values, or alterations in behavior. 

In addition to establishing a more robust versioning policy, zserio should also introduce a schema compatibility guideline that assists users in managing compatibility in terms of:

1. **Schema-specific API Compatibility**: The guideline should explain the mechanisms available for managing compatibility and outline best practices to achieve forward and backward compatibility during schema evolution.

2. **Schema-specific Data Compatibility**: The guideline should also clarify the mechanisms for managing data compatibility and illustrate how users can ensure forward and backward compatibility during schema evolution.

When discussing these changes, consider the following:

1. The implications of different zserio versions.
2. The impact of schema versions and how they interact with zserio versions.
3. The API generated with specific combinations of zserio and schema versions.
4. The data generated with specific combinations of zserio and schema versions.

Furthermore, we need to improve transparency and communication with users. Users should be able to easily identify when specific issues necessitate incompatible changes (e.g., through the use of tags) as well as when releases introduce incompatible changes. Depending on the complexity of these changes, we may need to provide additional upgrade instructions to aid users in transitioning to the new version.

**Comment by MisterGC** [comment]
What about Extension APIs (for example when somebody develops support for another language)?

**Comment by mikir** [comment]
We suggest to create Zserio compatibility guide with the following sections:

- Schema Language Compatibility
- Extension Compatibility
- Code Generator Compatibility
- Runtime Generator Compatibility
- Binary Encoding Compatibility
- JSON Encoding Compatibility
- Command Line Compatibility

Each section will contain definition of the compatibility and the detail desription how it is possible to follow this compatibility.

**Comment by mikir** [comment]
New [Zserio Compatibility Guide](https://github.com/ndsev/zserio/blob/master/doc/ZserioCompatibilityGuide.md) has been introduced. This document describes all possible backward incompatibilities that can occur after updating of Zserio:

- **Schema Language Compatibility** determines whether new Zserio versions can compile old schemas
- **Extension API Compatibility** determines whether a Zserio extension is compatible with the Zserio core
- **Code Generator Compatibility** determines whether code generated by a Zserio extension is compatible with code generated by older Zserio extensions
- **Binary Encoding Compatibility** determines whether new Zserio code generator versions serialize the data to the same binary stream as old Zserio code generator versions
- **JSON Encoding Compatibility** determines whether new Zserio code generator versions export the data to the same JSON file as previous Zserio code generator versions
- **Command Line Compatibility** determines whether new Zserio versions support the same command line arguments as previous Zserio versions
