### ISSUE TITLE
Wrong unresolved referenced symbol warning in documentation comment

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#458]
Consider the following schema:

main.zs:

```
package main;

import imported.*;
```

imported.zs:

```
/*! This is a link to [main module](main.zs). !*/
package imported;
```

Then zserio compilation by using command

```
java -jar zserio.jar main.zs -setTopLevelPackage top
```

gives wrong warning

```
[WARNING] imported.zs:1:19: Documentation: Unresolved referenced symbol 'top.main'! [doc-comment-see]
```

This warning is not fired when `-setTopLevelPackage` command line option is not used.

**Comment by Mi-La** [comment]
Note that **[doc-comment-see]** will be changed to **[doc-comment-link]** since it should fit to both classic and markdown documentation comments.
