### ISSUE TITLE
cpp: It seems that it is not compatible with Windows header files.

### ISSUE THREAD

**Issue by kancve** [ndsev/zserio#463]
When I integrate zserio into a custom project, it seems that it is not compatible with Windows header files.

More information can be found [here](https://github.com/kancve/zserio-cpp-test).

**Comment by kancve** [comment]
I'm sorry I forgot to commit it to [github](https://github.com/kancve/zserio-cpp-test/blob/master/docs/assets/windows_error.png).

![windows_error.png](https://github.com/kancve/zserio-cpp-test/blob/master/docs/assets/windows_error.png)

**Comment by kancve** [comment]
I checked the [relevant materials](https://blog.csdn.net/qq_17291647/article/details/104230809) and found that this is a common problem. The max/min macro conflicts.

I use parentheses to enclose std::max, It seems a good way to avoid macro substitution. More information can be found [here](https://github.com/kancve/zserio-cpp-test/commit/0ce7521f95c3ec7843abc2b2ab68eafc84eabb02).

**Comment by mikir** [comment]
Thank you very much to point this out, kancve!

Because we would like to avoid patching of our runtime library just because of `windows.h` internal problem, it will be probably better to define macro `NOMINMAX` before `#include <windows.h>`. Could you please so kind and check this solution as well?

**Comment by kancve** [comment]
> Thank you very much to point this out, kancve!
> 
> Because we would like to avoid patching of our runtime library just because of `windows.h` internal problem, it will be probably better to define macro `NOMINMAX` before `#include <windows.h>`. Could you please so kind and check this solution as well?

Yes, each of the three schemes has its advantages and disadvantages, which is suitable for its own project.
