### ISSUE TITLE
No difference between explicit and implicit (auto-) values of enum members.

### ISSUE THREAD

**Issue by MisterGC** [ndsev/zserio#468]
zserio generated HTML docs contain enum values also for auto-generated/implicitly assigned enum values. This is misleading and can be confusing when talking about the enum values, because it creates the impression that schema authors have explicitly decided to assign value. But exactly the opposite is the case, schema authors use this feature with "I don't care about the actual value, but assume that zserio keeps it stable as long as the position of the  element doesn't change" in mind.

Example:
``` C
enum uint8 Colors
{
  RED,
  GREEN,
  BLUE
};
```
Generate the HTML docu and the result will contain `RED = 0, GREEN = 1 and BLUE = 2` as if the author did that explicitly.

**Suggestion**: Omit these values in this case, the author intended that users should not care about the actual value when studying the schema. 

In case there are users who really need the value the explicit assignment could be commented `// = 1, assigned implicitly'

**Comment by mikir** [comment]
All not defined enumeration values are shown greyed now and are hideable by clicking hiding documentation icon.

**Comment by MisterGC** [comment]
Can you please exclude the values completely (see my motivation above)?

**Comment by mikir** [comment]
OK. We will reopen it.

**Comment by MisterGC** [comment]
yes, imo it is - one extension could be an option to activate the values in the docs would be possible (false by default), but even then I would clearly indicate that they have not been assigned explicitly.
