### ISSUE TITLE
Fields in choice or union expressions are wrongly resolved

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#47]
Choice and union types do not have available all fields. Therefore the following should not be compileable:

```
package bad_constraint_error;

enum uint8 Selector
{
    BLACK,
    GREY,
    RED
};

choice EnumParamChoice(Selector selector) on selector
{
    case Selector.BLACK:
        int8 black;

    case GREY:
        int16 grey : black > 0 && grey > 0; // ERROR because 'black' is not available!

    default:
        int64 other;
};
```

**Comment by fklebert** [comment]
Just to make sure: The problem here is not the missing RED value in the case, but the constraint in the GRAY case which does not have access to `black`, right?

**Comment by mikir** [comment]
> Just to make sure: The problem here is not the missing RED value in the case, but the constraint in the GRAY case which does not have access to `black`, right?
Yes, correct. This works for normal structures but does not for choices and unions where other fields are not available. Very similar problem can occur for functions.

**Comment by mikir** [comment]
We will do it ASAP to be in 1.1.0 because we can fix it quickly.
