### ISSUE TITLE
Add a description about the JSON mapping used by zserio

### ISSUE THREAD

**Issue by MisterGC** [ndsev/zserio#471]
Currently, there is no clear documentation or description about the JSON mapping used by zserio. This makes it difficult for users to understand how the data is being mapped from the binary format to JSON and vice versa.

It would be beneficial to have a clear documentation or description about the JSON mapping used by zserio, including information such as:

- The mapping of the different types (e.g. integers, strings, etc.)
- The handling of optional and default values
- The handling of enums and bitmasks
- The handling of 64-bit integers and floating-point numbers
- Any known limitations or issues with the JSON mapping

This information would make it easier for users to understand how the data is being mapped and how to correctly interpret the JSON data, improving the overall usability of zserio.

A section in the existing documentation (or the encoding guide?) would be sufficient to cover this topic.

**Comment by mikir** [comment]
The Zserio JSON guide is available [here](https://github.com/ndsev/zserio/blob/master/doc/ZserioJsonGuide.md).
