### ISSUE TITLE
Extended GitHub Actions configuration needed.

### ISSUE THREAD

**Issue by MisterGC** [ndsev/zserio#472]
At the moment of writing this issue the GitHub Actions configuration only covers Ubuntu 20.04 and Python 3.8. This is too limited both regarding testing the supported platforms as well as potentially providing more release artifact variants. As the upcoming support for C++ runtime bindings for zserio Python demands also special builds/packaging for different Python versions (because of ABI compatibility), this is even more important. 

Have a look at the [zswag GitHub Actions configuration](https://github.com/ndsev/zswag/blob/master/.github/workflows/cmake.yml) as a reference.

**Comment by mikir** [comment]
Please note that the Ubuntu 18.04 actions runner image will be fully unsupported by 2023/04/01.
