### ISSUE TITLE
Solve backward compatible extension at the end of top level structures

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#482]
The forward compatibility after extension at the end of top level structures works automatically. This is because the parsing always stops as soon as all fields are parsed even if there are some unread bits left in the bit stream.

However, the backward compatibility of such extension does not work. One solution could be to introduce new schema keyword which would indicate optional extension which does not have to be encoded in the bit stream at all. Example:

```
struct MyMessage
{
    bit:6 someStuff;
    extend optional Extension extension;
};
```

Decoding of optional `extension` will be the same as normal optional field except of the fact that EOF does not mean parsing error but that optional `extension` is not there.

Usage of such extensions should be strictly limited only for top level structures which are not used anywhere as nested structure and only at the end.

**Comment by fklebert** [comment]
ad 1) I think this is not an issue. There are other means of checking the stream for corruptions like signatures etc. I think it also super-unlikely that a stream parses correctly in zserio and is still corrupt.

ad 2) Automatically aligning the `extend` keyword to the next byte (align(8)) would fix this. I think it is anyhow a good idea to align automatically before `extend`

ad 3) I think it is totally fine to only allow one extend at the end of the toplevel structure. In case you need more extension over time you need to simply add a compound structure after `extend` and then change this. This results of course in a base version + extension version to be readable and cannot be used for 3 different parsers but only one, but that is fine. Of course this drawback should be documented well enough.

ad 4) Correct. That was even originally stated in your first issue description I think.

ad 5) not relevant any longer if we only allow exactly one extend

ad 6) 👍  but the workaround would be to wrap them in a compound I guess.

**Comment by mikir** [comment]
Thanks a lot for the feedback!

ad 1) OK

ad 2) Good idea, thanks. It will be much easier from implementation point of view just to align automatically before `extend` and not to try calculate the bit size of extended data (bit size is not available in general during zserio compilation).

ad 3) OK, I see. However, the implementation of multiple `extend` commands is not a big problem. Even if this is not needed for now, it would be easier for us to allow it immediatelly without any need to open this issue again in the future. In all cases, we will have to document properly the usage.

ad 6) Yes, wrapping is always possible.

**Comment by mikir** [comment]
The new keyword `extend` has been implemented for all generators. Any feedback before release from user point of view will be appreciated.
