### ISSUE TITLE
Add method to retrieve enum value from enum string directly

### ISSUE THREAD

**Issue by fklebert** [ndsev/zserio#487]
At the moment the zserio runtime only provides a way to get a string from the enum value:
https://zserio.org/doc/runtime/cpp/Enums_8h_source.html#l00078

In some cases it is beneficial to also have this the other way around. Like a method `StringToValue`, which would check whether the provided string fits any of the enum traits names.

Background to this request is the following: When trying to map enum symbol names which do not have the same enum value (underlying value). In such a case one needs to work with the enum traits today, which are kind of undocumented.

**Comment by Mi-La** [comment]
`ZserioTreeCreator` currently uses type info in [`makeAnyEnumValue`](https://github.com/ndsev/zserio/blob/d158c3e6b6cdd19d6f4572c6defa812d219898f5/compiler/extensions/cpp/runtime/src/zserio/ZserioTreeCreator.h#L183), but it also isn't straightforward.

**Comment by mikir** [comment]
OK, I've planned this for the next milestone.
