### ISSUE TITLE
Provide test coverage statistics in release assets

### ISSUE THREAD

**Issue by fklebert** [ndsev/zserio#491]
Provide the following statistics for test coverage of the zserio runtime if they can be generated by an appropriate tool:
- Function coverage
- Region coverage
- Line coverage
- Branch coverage

The report shall be added to the release assets in a nice readable way (e.g. HTML)
Would also be nice if we can get a bagde for the readme, but if that is not straightforward, just ignore.

**Comment by mikir** [comment]
We have integrated test coverage reports directly to the runtime documentation:

C++ - https://zserio.org/doc/runtime/cpp
Java - https://zserio.org/doc/runtime/java
Python - https://zserio.org/doc/runtime/python

Direct links to test coverage reports:

C++ gcc - https://zserio.org/doc/runtime/cpp/coverage/gcc
C++ clang - https://zserio.org/doc/runtime/cpp/coverage/clang
Java - https://zserio.org/doc/runtime/java/coverage
Python - https://zserio.org/doc/runtime/python/coverage

As a consequence, test coverage reports will be distributed in each release together with runtime documentation stored in `zserio-[version]-runtime-libs.zip` file.

GitHub badges for test coverage (C++ gcc, C++ clang, Java and Python) will be available as well.

**Comment by Roland-Homeier** [comment]
@mikir I assume it is only for the code of the runtime lib - correct? For my understanding these test are required for getting it "ASIL certificated" for the generated source code as well.
@fklebert : FYI

**Comment by mikir** [comment]
Yes, correct. This is only for code in runtime libraries.

Generated code is another story. Such tests depend on the underlying schema, used zserio compiler options and used database and on the application.
