### ISSUE TITLE
BoolArray doesn't work with bool elements and uses uint8_t instead

### ISSUE THREAD

**Issue by Mi-La** [ndsev/zserio#50]
To prevent usage of `std::vector<bool>` our `BoolArray` is based on `uint8_t`. It might be good for performance, but user would expect to get a `bool` type when accessing an element -> e.g. `boolArray.elementAt(0)`.
If we want to use another underlying type than `bool`, we should be able to provide `bool` on the container's interface.

Currently we disabled MSVC warning C4800: forcing value to bool 'true' or 'false' (performance warning), because the generated code fires the warning when a `BoolArray` is used as a parameter in a parameterized type.

**Comment by mikir** [comment]
New C++11 Emitter already uses STL bool vector. Old C++98 Emitter won't be fixed because it's deprecated.
