### ISSUE TITLE
zserio logo not suitable for dark mode.

### ISSUE THREAD

**Issue by MisterGC** [ndsev/zserio#500]
Currently parts of the logo are barely visible when using GitHub dark mode, therefore I suggest to use a logo which works for both light and dark mode.

Current state:
![image](https://user-images.githubusercontent.com/2118573/234020122-3c7ef58d-bca0-4a0a-a6cb-e14be726de9a.png)

**Comment by mikir** [comment]
Thanks to figure it out. We will pay attention on that.
