### ISSUE TITLE
How to mapping blob column after 2.9.0

### ISSUE THREAD

**Issue by wsndbd** [ndsev/zserio#502]
My SQL table is defined as follows:

CREATE TABLE JunctionArea (
    JA_ID      BIGINT,
    MESH       INTEGER,
    RN_GROUP   TEXT DEFAULT "",
    TYPE       TEXT DEFAULT "",
    GEOMETRY   BLOB,
    MEMO       TEXT NOT NULL DEFAULT "",
    PRIMARY KEY (JA_ID)
)
Before version 2.9.0, I defined the following in my .zs file:

struct BlobData {
    implicit int8 data[];
};

sql_table JunctionAreaTable {
    int64 JA_ID;
    int32 MESH;
    string RN_GROUP;
    string TYPE;
    BlobData GEOMETRY;
    string MEMO;
};
By using the implicit keyword, I can correctly read the GEOMETRY field with the following statement:

nv.sq3.junction.BlobData blobData = row.getGEOMETRY();

However, after version 2.9.0, I can only define the following in my .zs file:

struct BlobData {
    bytes data;
};

sql_table JunctionAreaTable {
    int64 JA_ID;
    int32 MESH;
    string RN_GROUP;
    string TYPE;
    BlobData GEOMETRY;
    string MEMO;
};
This is because the implicit keyword has been removed. But now, I cannot read the blobData field content correctly using:

nv.sq3.junction.BlobData blobData = row.getGEOMETRY();

How can I solve this issue?

**Comment by mikir** [comment]
If I understood the problem correctly, you are using data created using schema with `implicit` for schema with `bytes`. This won't work because `bytes` is encoded in different way as `implicit`. If this is a case, you should continue using `implicit` and force zserio to accept it during compilation by command line argument `-allowImplicitArrays`.

**Comment by wsndbd** [comment]
> If I understood the problem correctly, you are using data created using schema with `implicit` for schema with `bytes`. This won't work because `bytes` is encoded in different way as `implicit`. If this is a case, you should continue using `implicit` and force zserio to accept it during compilation by command line argument `-allowImplicitArrays`.

Thank you, this solved my problem.
