### ISSUE TITLE
ZSERIO_RUNTIME_64BIT looks obsolete in 2.11.0

### ISSUE THREAD

**Issue by AntonSulimenkoHarman** [ndsev/zserio#519]
https://github.com/ndsev/zserio/blob/v2.11.0/compiler/extensions/cpp/runtime/src/zserio/BitStreamReader.cpp

2.11.0 introduces static_assert that makes ZSERIO_RUNTIME_64BIT not usable.
It's impossible to set 32bit for a 64-bit platform and vice versa.
```c++
#ifdef ZSERIO_RUNTIME_64BIT
    using BaseType = uint64_t;
    using BaseSignedType = int64_t;
#else
    using BaseType = uint32_t;
    using BaseSignedType = int32_t;
#endif

    static_assert(sizeof(uintptr_t) == sizeof(BaseType), "Unexpected uintptr_t sizeof!");
```

My proposal is to do this switch completely internally in code:
```c++
#if UINTPTR_MAX == 0xFFFFFFFFFFFFFFFFull
    typedef uint64_t BaseType;
    typedef int64_t BaseSignedType;
#elif UINTPTR_MAX == 0xFFFFFFFFu
    typedef uint32_t BaseType;
    typedef int32_t BaseSignedType;
#else
    #error Unexpected uintptr_t sizeof!
#endif
```

**Comment by mikir** [comment]
Thanks to pointing this out. It might be probably better than current solution.

> It's impossible to set 32bit for a 64-bit platform and vice versa.
Yes, we do not support this. Are you able to see any use case where this feature can be usefull?
