### ISSUE TITLE
zserio_ant_task.compile jdk17 deprecation on AccessController

### ISSUE THREAD

**Issue by Dennis-NavInfo** [ndsev/zserio#520]
When compiling zserio v2.11.0 the following issue was observed:
```
./build.sh core java java_rt zserio

...

{noformat}zserio_ant_task.compile:
    [mkdir] Created dir: /tmp/zserio/build/ant_task/classes
    [javac] Compiling 4 source files to /tmp/zserio/build/ant_task/classes
    [javac] /tmp/zserio/ant_task/src/zserio/ant/ToolWrapper.java:86: warning: [removal] AccessController in java.security has been deprecated and marked for removal
    [javac]             final ClassLoader classLoader = AccessController.doPrivileged(classLoaderCreator);
    [javac]                                             ^
    [javac] error: warnings found and -Werror specified
    [javac] 1 error
    [javac] 1 warning

BUILD FAILED
/tmp/zserio/ant_task/build.xml:51: Compile failed; see the compiler error output for details.
{noformat}
```
For this attempt openjdk17 was used. Compiling with an older JDK (11) worked without showing this issue.

**Comment by mikir** [comment]
Thank you very much for pointing this out. We will pay attention to that. We currently don't use such new Java compiler but sooner or later we will have to. :-)

**Comment by Mi-La** [comment]
Whole the `AccessController` machinery was added only to suppress FindBugs / SpotBugs warning. We can probably just remove it and everything should work.
But note that Java 17 is not officially supported and tested and we even cannot run our version of SpotBugs (3.1.12) with Java 17. The only officially supported and tested version is Java 8.
