### ISSUE TITLE
Optimize memory allocations for packed arrays

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#524]
In case of packed arrays of structures, Packing Context structure is allocated dynamically for all packable compound fields. 
In case of packed array of choices and unions, Packing Context structure is allocated dynamically for all possible cases (fields).

In case of many packed arrays of compounds (e.g. in case of packed array of compounds which contain again packed arrays), the following drawbacks have been observed:

1. Too big total allocated memory for all Packing Context structures.
2. Too many small allocations for Packing Context structures.

Consider to redesign packing implementation in generated code to contain whole tree hierarchy of Packing Context structures similarly to zserio objects hierarchy. This solution will

- decrease number of small memory allocations for Packing Context structures (will be allocated only once per each packed array) and
- eliminate the unnecessary allocated Packing Context structures for unpackable fields in choice/union cases

**Comment by Mi-La** [comment]
This will probably solve #498, since we will have the whole (redesigned) packing context on stack. We should document how to estimate required stack size based on a schema.

**Comment by mikir** [comment]
The memory allocations for packed arrays have been heavily optimized. The following improvements have been observed for very complicated packed arrays:

| Language | Memory reduction | Speed improvements |
|--------------- | --------------------------- |---------------------------------|
| C++            | 90.99%                     | 86.96%                           |
| Java           | 62.63%                     | 37.96%                           |
| Python      | 4.67%                       | 27.26%                           |
