### ISSUE TITLE
Enhance unpackable warning to report clearly that packed keyword is ignored

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#525]
Currently, if some compound type is used in packed array as an element and it does not contain any packable field, zserio compiler fires warning "`'CompoundType' doesn't contain any packable field.`".

However, this warning actually means that packed array won't be packed at all and keyword `packed` will be ignored. As a consequence, such packed array will be encoded as a normal array in the bit stream without any addional `isPacked` bit.

It would be better to enhance this unpackable warning to report users clearly that `packed` keyword will be ignored.

Don't forget to enhance warnings documentation as well because of this change. Moreover, it would be good to document behaviour of union types. Union types are always packable because underlying hidden choice tag (encoded as a `varsize`) is packable.

**Comment by Mi-La** [comment]
see also #528
