### ISSUE TITLE
Zserio Conan 2.x Deployment and Integration of CMake Helper

### ISSUE THREAD

**Issue by josephbirkner** [ndsev/zserio#533]
As the NDS Joint Tooling Dev Team has decided that we want to migrate our dependencies to Conan 2, both zserio and zswag also need to be deployed to Conan center at some point. Currently, we use our [zserio-cmake-helper](github.com/klebert-engineering/zserio-cmake-helper) repo to pull in zserio as a dependency. This also gives us the `add_zserio_library()` cmake function. It would be awesome if this (or a similar) utility was also part of the official Conan deployment.

**Comment by Mi-La** [comment]
Zserio is now available in Conan Center: [![Conan Center](https://img.shields.io/conan/v/zserio)](https://conan.io/center/recipes/zserio)
