### ISSUE TITLE
'-withSourcesAmalgamation' seems not work properly under ubuntu 18.04

### ISSUE THREAD

**Issue by chenbd** [ndsev/zserio#537]
Hello,
Current we are using zserio to develop nds.live.
And i found that some generated cpp source files missing some functions which lead linker error when build.
The error goes into 'core/attributemap/Attributemap.cpp' and 'core/grid/Grid.cpp'.
i run zserio.jar by:
```
java -jar ../../../../../tools/zserio/bin/zserio.jar  -setTopLevelPackage nds -src . -cpp ../src  path_to_zs_file
```

This happened for both runtime version 2.12.0 and 2.11.0.

As a work around, i must add '-withoutSourcesAmalgamation' which result more build time.

Would you please check this issue?

**Comment by chenbd** [comment]
When ***path_to_zs_file*** set as ***all.zs***, generated cpp files are ok.
The issue happened only when loop all ".zs" files under different path without specify ***all.zs***.

**Comment by mikir** [comment]
I don't think that it is allowed to compile NDS sources differently than specifing root source `all.zs`.

In case of any doubts regarding NDS sources, please contact NDS directly, e.g. via NDS support e-mail.

**Comment by chenbd** [comment]
Thanks for your answer.
Specify ***all.zs*** seems the right way to generate cpp source files.
when loop all .zs files, need  with ***'-withoutSourcesAmalgamation' ***.
Close this issue.
