### ISSUE TITLE
Json: Scientific notation decode error

### ISSUE THREAD

**Issue by wy0wxb** [ndsev/zserio#559]
zserio_runtime\zserio\JsonDecoder.h

![20231228-104430](https://github.com/ndsev/zserio/assets/102043540/5d07f127-93c6-4286-840a-41b795c7d39d)
![image](https://github.com/ndsev/zserio/assets/102043540/40548eaa-a592-42b6-9572-71ff5a67f90e)

**Comment by mikir** [comment]
Thanks for pointing this out! We will fix it in the current milestone.
