### ISSUE TITLE
Add support for Python 3.12

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#567]
Currently, the Python generator support Python 3.8, 3.9, 3.10 and 3.11. Please add support even for the newest Python 3.12.

Don't forget to update 'Supported Python Version' section in [README.md](https://github.com/ndsev/zserio/blob/master/compiler/extensions/python/README.md#supported-python-version).

**Comment by Mi-La** [comment]
What about [zserio-pypi](https://github.com/ndsev/zserio-pypi)? Does it need to be updated as well?
