### ISSUE TITLE
less than operator is missing for features datatypes

### ISSUE THREAD

**Issue by Roland-Homeier** [ndsev/zserio#570]
We are missing the less than for features datatypes like lane group to sort according to the id with Zserio 2.13.

In addition, we could find the not equal operator.

Is it possible to add them during the code generation?

**Comment by mikir** [comment]
Zserio 2.13 already supports C++ less than operator: #288. I guess it should be enough to regenerate schema by the newest Zserio release.

Regarding not equal operator, we have decided not to implement it to keep generated object as simple as possible (generated objects are already complicated enough). C++ users can for example use `std::rel_ops::operator!=,>,<=,>=` to overcome this limitation. However, in case of any strong need please create a new issue (or we can reuse this one).

**Comment by mikir** [comment]
I'll close this issue. In case of further problem, please raise a new issue or create a question in discussion.
