### ISSUE TITLE
Enable conversion warnings for gcc compiler

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#579]
Enable conversion warnings (`-Wconversion`) for gcc compiler and solve all findings everywhere. Example from C++ runtime library:

```
compiler/extensions/cpp/runtime/src/zserio/BitStreamWriter.cpp: In member function ‘void zserio::BitStreamWriter::writeUnsignedBits(uint32_t, uint8_t)’:
compiler/extensions/cpp/runtime/src/zserio/BitStreamWriter.cpp:558:56: error: conversion from ‘unsigned int’ to ‘uint8_t’ {aka ‘unsigned char’} may change value [-Werror=conversion]
  558 |         const uint8_t maskedByte = m_buffer[byteIndex] & ~(0xFFU >> bitsUsed);
```

**Comment by mohammedRafeeque** [comment]
Thanks for creating the reported issue for resolving conversion warnings for gcc compiler.

Thanks & Regards
Rafeeque (Bosch)

**Comment by mikir** [comment]
We have fixed all conversion warnings which are fired from GCC 7.5.0 compiler in case of option ‘-Wconversion’.  However, this option gives warning even for the following constructs:

```
char c = 1;
char c2 = 2;
c += c2; // warning: conversion to ‘char’ from ‘int’ may alter its value
```

Such warnings are not very usefull, therefore GCC 10.0 and newer versions are not so strict but has introduced new option `-Warith-conversion` because of that. Therefore, we recommend upgrade to GCC 10.0.
