### ISSUE TITLE
Add below ruleset to SonarCloud MISRA 2023 Configuration

### ISSUE THREAD

**Issue by mohammedRafeeque** [ndsev/zserio#585]
Following Ruleset part of MISRA 2023 are not available in SonarCloud MISRA2023 configuration.
Please check and update the configuration to include this list.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mor4kor/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mor4kor/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

RuleId | SevrityLevel | Rulenumber | Category | Description
-- | -- | -- | -- | --
MISRACPP2023-15_0_1-a | 2 | Rule 15.0.1 | Required | Special member functions shall be provided   appropriately
MISRACPP2023-15_1_3-a | 2 | Rule 15.1.3 | Required | Conversion operators and constructors that   are callable with a single argument shall be explicit
MISRACPP2023-18_2_2-a | 2 |   | Required |  
MISRACPP2023-5_10_1-e | 2 | Rule 5.10.1 | Required | User-defined identifiers shall have an   appropriate form
MISRACPP2023-6_4_1-a | 2 | Rule 6.4.1 | Required | A variable declared in an inner scope shall not hide a variable   declared in an outer scope
MISRACPP2023-6_4_1-c | 2 | Rule 6.4.1 | Required | A variable declared in an inner scope shall not hide a variable   declared in an outer scope
MISRACPP2023-7_0_3-a | 2 | Rule 7.0.3 | Required | The numerical value of a character shall not   be used
MISRACPP2023-7_0_4-a | 2 | Rule 7.0.4 | Required | The operands of bitwise operators and shift   operators shall be appropriate
MISRACPP2023-7_0_5-a | 2 | Rule 7.0.5 | Required | Integral promotion and the usual arithmetic   conversions shall not change the signedness or the type category of an   operand
MISRACPP2023-7_0_6-a | 2 | Rule 7.0.6 | Required | Assignment between numeric types shall be   appropriate
MISRACPP2023-8_2_5-a | 2 | Rule 8.2.5 | Required | reinterpret_cast shall not be used
MISRACPP2023-8_2_6-a | 2 | Rule 8.2.6 | Required | An object with integral
MISRACPP2023-9_3_1-a | 2 | Rule 9.3.1 | Required | The body of an iteration-statement or a   selection-statement shall be a compound-statement
MISRACPP2023-9_3_1-b | 2 | Rule 9.3.1 | Required | The body of an iteration-statement or a   selection-statement shall be a compound-statement

</body>

</html>

Following MISRA Rules sets are already integrated in SonarCloud MISRA2023 configuration. But there are no warnings/Error reported.
But our internal run using parasoft tool reporting warning with severity level 2. 
Please check is this rules are getting suppressed or why there are no warning detected in SonarCloud SCA runs.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mor4kor/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mor4kor/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

RuleId | SevrityLevel | Rulenumber | Category | Description | Covered by Sonar could?
-- | -- | -- | -- | -- | --
MISRACPP2023-0_1_2-a | 2 | Rule 0.1.2 | Required | The value returned by a function shall be   used | yes
MISRACPP2023-11_6_2-a | 2 | Rule 11.6.2 | Mandatory | The value of an object must not be read   before it has been set | yes
MISRACPP2023-12_3_1-a | 2 | Rule 12.3.1 | Required | The union keyword shall not be used | yes
MISRACPP2023-19_2_2-a | 2 | Rule 19.2.2 | Required | The #include directive shall be followed by   either a <filename> or "filename" sequence | yes
MISRACPP2023-28_6_2-a | 2 | Rule 28.6.2 | Required | Forwarding references and std::forward shall   be used together | yes
MISRACPP2023-6_7_1-a | 2 | Rule 6.7.1 | Required | Local variables shall not have static   storage duration | yes
MISRACPP2023-6_7_2-a | 2 | Rule 6.7.2 | Required | Global variables shall not be used | yes
MISRACPP2023-8_2_2-a | 2 | Rule 8.2.2 | Required | C-style casts and functional notation casts   shall not be used | yes

</body>

</html>

**Comment by mikir** [comment]
Unfortunately, there is no direct mapping of the MISRA C++ 2023 rules to [SonarCloud rules](https://sonarcloud.io/organizations/ndsev/rules?languages=cpp). Although SonarCloud rules can be filtered out by tag "misra-c++2023", it does not mean that you will get **ALL** MISRA C++ 2023 rules (actually, there are only 58 of them). Other MISRA C++ 2023 rules might be hidden by different tags like "based-on-misra".

As an example please have a look to SonarCloud rule '["explicit" should be used on single-parameter constructors and conversion operators](https://sonarcloud.io/organizations/ndsev/rules?open=cpp%3AS1709&rule_key=cpp%3AS1709)' which has tag "based-on-misra".

Such mapping of all 179 MISRA C++ 2023 rules is not available and we don't have enough capacity to investigate it.

However, I would suggest the following approach:

- We will start with **ZERO** Sonar Cloud rules for C++ Zserio Runtime
- If you identify some MISRA C++ 2023 rule using your internal tool which is really necessary to fix, you will create a dedicated issue at GitHub (one rule, one issue)
- Ideally, you will try to identify the corresponding rule in SonarCloud
- We will add this rule to SonarCloud configuration
- We will try to fix it keeping number of SonadCloud findings to **ZERO**
- If there is no corresponding rule in SonarCloud or if this rule does not report all issues which your internal tool, we will have to discuss it rule by rule

This suggested approach will prevent us from having hundreds or thousands SonarCloud issues waiting to fix in Zserio, which is far beyond our capacity.

If you agree with this approach, we will do it in this way and I will close this issue. As a good start is already created #586 (I will split it up to two issues).
