### ISSUE TITLE
Fix MISRA C++ 2023 rule 8.2.5 "reinterpret_cast shall not be used"

### ISSUE THREAD

**Issue by mohammedRafeeque** [ndsev/zserio#586]
**Zserio version and language**
Zserio: latest from master 
Language: C++

**Describe the bug**
Check and resolve SCA warning MISRACPP2023-8_2_5-a ("reinterpret_cast shall not be used") reported in Zserio on C++ runtime library.

Rule ID | severity | Message | Path | Line | Link to sonarcloud
-- | -- | -- | -- | -- | --
MISRACPP2023-8_2_5-a | 2 | reinterpret_cast' should not be   used | /zserio_runtime/src/roadgraph_reliable/zserio_runtime/zserio/FileUtil.cpp | 17 | https://sonarcloud.io/project/issues?open=AY3k4v8yXMcagTJBbG3h&id=ndsev_zserio
MISRACPP2023-8_2_5-a | 2 | reinterpret_cast' should not be   used | /zserio_runtime/src/roadgraph_reliable/zserio_runtime/zserio/FileUtil.cpp | 42 | https://sonarcloud.io/project/issues?open=AY3k4v8yXMcagTJBbG3j&id=ndsev_zserio
MISRACPP2023-8_2_5-a | 2 | 'reinterpret_cast' should not be   used | /zserio_runtime/src/roadgraph_reliable/zserio_runtime/zserio/FloatUtil.cpp | 164 | https://sonarcloud.io/project/issues?open=AY3k4v9QXMcagTJBbG4N&id=ndsev_zserio
MISRACPP2023-8_2_5-a | 2 | reinterpret_cast' should not be   used | /zserio_runtime/src/roadgraph_reliable/zserio_runtime/zserio/FloatUtil.cpp | 171 | https://sonarcloud.io/project/issues?open=AY3k4v9QXMcagTJBbG4P&id=ndsev_zserio
MISRACPP2023-8_2_5-a | 2 | reinterpret_cast' should not be   used | /zserio_runtime/src/roadgraph_reliable/zserio_runtime/zserio/FloatUtil.cpp | 178 | https://sonarcloud.io/project/issues?open=AY3k4v9QXMcagTJBbG4R&id=ndsev_zserio
MISRACPP2023-8_2_5-a | 2 | reinterpret_cast' should not be   used | /zserio_runtime/src/roadgraph_reliable/zserio_runtime/zserio/FloatUtil.cpp | 185 | https://sonarcloud.io/project/issues?open=AY3k4v9QXMcagTJBbG4T&id=ndsev_zserio

**How to reproduce**
see the sonarcloud links

**Expected behavior**
No SCA warnings for MISRA 2023 ruleset

**Additional context**

**Comment by mohammedRafeeque** [comment]
@mikir @Roland-Homeier  FYI:

**Comment by CheisonShweta** [comment]
Adding to the above list there are 2 more occurrences for MISRACPP2023-15_1_3-a.
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/FWC1KOr/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/FWC1KOr/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


Rule ID | Severity | Message | Path | Line | Link to   sonarcloud  
-- | -- | -- | -- | -- | --
MISRACPP2023-15_1_3-a | 2 | Constructor 'UniquePtrDeleter' allowing conversion should be made   explicit | /zserio_runtime/include/roadgraph_reliable/zserio_runtime/zserio/UniquePtr.h | 57 | https://sonarcloud.io/project/issues?open=AY3k4v99XMcagTJBbG5C&id=ndsev_zserio |   |  
MISRACPP2023-15_1_3-a | 2 | Constructor 'UniquePtrDeleter' allowing conversion should be made   explicit | /zserio_runtime/include/roadgraph_reliable/zserio_runtime/zserio/UniquePtr.h | 68 | https://sonarcloud.io/project/issues?open=AY3k4v99XMcagTJBbG5D&id=ndsev_zserio |   |  
</body>

</html>

**Comment by mikir** [comment]
> Adding to the above list there are 2 more occurrences for MISRACPP2023-15_1_3-a.

This will be fix within scope of #593.

**Comment by mikir** [comment]
We have got rid of `reinterpret_cast` whenever it was possible.

However, the following **8 SonarCloud issues** in the C++ runtime library have been **accepted as the exceptions**:

Module | Line | Command | Link
-- | -- | -- | --
AnyHolder.h | 181 | `reinterpret_cast<detail::NonHeapHolder<T, ALLOC>*>( &m_untypedHolder.inPlace);` | [SonarCloud](https://sonarcloud.io/project/issues?resolutions=WONTFIX&id=ndsev_zserio&open=AY3k4v-LXMcagTJBbG5U&tab=code)
AnyHolder.h | 827 | `reinterpret_cast<const detail::NonHeapHolder<T, ALLOC>*>( &m_untypedHolder.inPlace);` | [SonarCloud](https://sonarcloud.io/project/issues?resolutions=WONTFIX&id=ndsev_zserio&open=AY3k4v-LXMcagTJBbG5V)
AnyHolder.h | 857 | `reinterpret_cast<detail::IHolder<ALLOC>*>( &m_untypedHolder.inPlace)` | [SonarCloud](https://sonarcloud.io/project/issues?resolutions=WONTFIX&id=ndsev_zserio&open=AY3k4v-LXMcagTJBbG5W)
AnyHolder.h | 864 | `reinterpret_cast<const detail::IHolder<ALLOC>*>( &m_untypedHolder.inPlace)` | [SonarCloud](https://sonarcloud.io/project/issues?resolutions=WONTFIX&id=ndsev_zserio&open=AY3k4v-LXMcagTJBbG5Y)
FileUtil.cpp | 17 | `reinterpret_cast<const char*>(buffer)` | [SonarCloud](https://sonarcloud.io/project/issues?resolutions=WONTFIX&id=ndsev_zserio&open=AY3k4v8yXMcagTJBbG3h)
FileUtil.cpp | 42 | `reinterpret_cast<char*>(bitBuffer.getBuffer()` | [SonarCloud](https://sonarcloud.io/project/issues?resolutions=WONTFIX&id=ndsev_zserio&open=AY3k4v8yXMcagTJBbG3j)
OptionalHolder.cpp | 628 | `reinterpret_cast<T*>(&m_inPlace);` | [SonarCloud](https://sonarcloud.io/project/issues?resolutions=WONTFIX&id=ndsev_zserio&open=AY3k4v9hXMcagTJBbG4h)
OptionalHolder.cpp | 638 | `reinterpret_cast<const T*>(&m_inPlace);` | [SonarCloud](https://sonarcloud.io/project/issues?resolutions=WONTFIX&id=ndsev_zserio&open=AY3k4v9hXMcagTJBbG4i)
