### ISSUE TITLE
Fix MISRA C++ 2023 rule 15.1.3 "Conversion operators and constructors that are callable with a single argument shall be explicit"

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#593]
**Zserio version and language**
Zserio: latest from master
Language: C++

**Describe the bug**
Check and resolve SCA warning MISRACPP2023-15_1_3-a ("Conversion operators and constructors that are callable with a single argument shall be explicit") reported in Zserio on C++ runtime library.

Rule ID | severity | Message | Path | Line | Link to sonarcloud
-- | -- | -- | -- | -- | --
MISRACPP2023-15_1_3-a | 2 | Constructor   'inplace_optional_holder' allowing conversion should be made explicit | /zserio_runtime/include/roadgraph_reliable/zserio_runtime/zserio/OptionalHolder.h | 670 | https://sonarcloud.io/project/issues?open=AY3k4v9hXMcagTJBbG4m&id=ndsev_zserio
MISRACPP2023-15_1_3-a | 2 | Constructor   'inplace_optional_holder' allowing conversion should be made explicit | /zserio_runtime/include/roadgraph_reliable/zserio_runtime/zserio/OptionalHolder.h | 678 | https://sonarcloud.io/project/issues?open=AY3k4v9hXMcagTJBbG4o&id=ndsev_zserio
MISRACPP2023-15_1_3-a | 2 | Constructor   'inplace_optional_holder' allowing conversion should be made explicit | /zserio_runtime/include/roadgraph_reliable/zserio_runtime/zserio/OptionalHolder.h | 689 | https://sonarcloud.io/project/issues?open=AY3k4v9hXMcagTJBbG4q&id=ndsev_zserio
MISRACPP2023-15_1_3-a | 2 | Constructor 'Span' allowing   conversion should be made explicit | /zserio_runtime/include/roadgraph_reliable/zserio_runtime/zserio/Span.h | 111 | https://sonarcloud.io/project/issues?open=AY3k4v9ZXMcagTJBbG4W&id=ndsev_zserio
MISRACPP2023-15_1_3-a | 2 | Constructor 'Span' allowing   conversion should be made explicit | /zserio_runtime/include/roadgraph_reliable/zserio_runtime/zserio/Span.h | 123 | https://sonarcloud.io/project/issues?open=AY3k4v9ZXMcagTJBbG4X&id=ndsev_zserio
MISRACPP2023-15_1_3-a | 2 | Constructor 'Span' allowing   conversion should be made explicit | /zserio_runtime/include/roadgraph_reliable/zserio_runtime/zserio/Span.h | 135 | https://sonarcloud.io/project/issues?open=AY3k4v9ZXMcagTJBbG4Y&id=ndsev_zserio
MISRACPP2023-15_1_3-a | 2 | Constructor 'Span' allowing   conversion should be made explicit | /zserio_runtime/include/roadgraph_reliable/zserio_runtime/zserio/Span.h | 147 | https://sonarcloud.io/project/issues?open=AY3k4v9ZXMcagTJBbG4Z&id=ndsev_zserio
MISRACPP2023-15_1_3-a | 2 | Constructor 'Span' allowing   conversion should be made explicit | /zserio_runtime/include/roadgraph_reliable/zserio_runtime/zserio/Span.h | 159 | https://sonarcloud.io/project/issues?open=AY3k4v9ZXMcagTJBbG4a&id=ndsev_zserio
MISRACPP2023-15_1_3-a | 2 | Constructor 'Span' allowing   conversion should be made explicit | /zserio_runtime/include/roadgraph_reliable/zserio_runtime/zserio/Span.h | 171 | https://sonarcloud.io/project/issues?open=AY3k4v9ZXMcagTJBbG4b&id=ndsev_zserio
MISRACPP2023-15_1_3-a | 2 | Constructor 'BasicStringView'   allowing conversion should be made explicit | /zserio_runtime/include/roadgraph_reliable/zserio_runtime/zserio/StringView.h | 54 | https://sonarcloud.io/project/issues?open=AY3k4v85XMcagTJBbG3l&id=ndsev_zserio
MISRACPP2023-15_1_3-a | 2 | Constructor 'BasicStringView'   allowing conversion should be made explicit | /zserio_runtime/include/roadgraph_reliable/zserio_runtime/zserio/StringView.h | 74 | https://sonarcloud.io/project/issues?open=AY3k4v85XMcagTJBbG3m&id=ndsev_zserio
MISRACPP2023-15_1_3-a | 2 | Constructor 'UniquePtrDeleter' allowing conversion should be made   explicit | /zserio_runtime/include/roadgraph_reliable/zserio_runtime/zserio/UniquePtr.h | 57 | https://sonarcloud.io/project/issues?open=AY3k4v99XMcagTJBbG5C&id=ndsev_zserio |   |  
MISRACPP2023-15_1_3-a | 2 | Constructor 'UniquePtrDeleter' allowing conversion should be made   explicit | /zserio_runtime/include/roadgraph_reliable/zserio_runtime/zserio/UniquePtr.h | 68 | https://sonarcloud.io/project/issues?open=AY3k4v99XMcagTJBbG5D&id=ndsev_zserio |   |  

**How to reproduce**
see the sonarcloud links

**Expected behavior**
No SCA warnings for MISRA 2023 ruleset

**Additional context**

**Comment by mikir** [comment]
We went through all implicit costructors in the C++ runtime library and they all have been **accepted as the exceptions**:

Module | Line | Command | Link
-- | -- | -- | --
OptionalHolder.h | 669 | `constexpr inplace_optional_holder(NullOptType) noexcept` | [SonarCloud](https://sonarcloud.io/project/issues?open=AY3k4v9hXMcagTJBbG4m&id=ndsev_zserio)
OptionalHolder.h | 677 | `inplace_optional_holder(const T& value)` | [SonarCloud](https://sonarcloud.io/project/issues?open=AY3k4v9hXMcagTJBbG4o&id=ndsev_zserio)
OptionalHolder.h | 688 | `inplace_optional_holder(T&& value)` | [SonarCloud](https://sonarcloud.io/project/issues?open=AY3k4v9hXMcagTJBbG4q&id=ndsev_zserio)
Span.h | 112 | `constexpr Span(element_type (&arr)[N]) noexcept` | [SonarCloud](https://sonarcloud.io/project/issues?open=AY3k4v9ZXMcagTJBbG4W&id=ndsev_zserio)
Span.h | 125 | `constexpr Span(std::array<U, N>& arr) noexcept` | [SonarCloud](https://sonarcloud.io/project/issues?open=AY3k4v9ZXMcagTJBbG4X&id=ndsev_zserio)
Span.h | 138 | `constexpr Span(const std::array<U, N>& arr) noexcept` | [SonarCloud](https://sonarcloud.io/project/issues?open=AY3k4v9ZXMcagTJBbG4Y&id=ndsev_zserio)
Span.h | 150 | `constexpr Span(std::vector<U, ALLOC>& vec)` | [SonarCloud](https://sonarcloud.io/project/issues?open=AY3k4v9ZXMcagTJBbG4Z&id=ndsev_zserio)
Span.h | 163 | `constexpr Span(const std::vector<U, ALLOC>& vec)` | [SonarCloud](https://sonarcloud.io/project/issues?open=AY3k4v9ZXMcagTJBbG4a&id=ndsev_zserio)
Span.h | 176 | `constexpr Span(const Span<U, N>& span) noexcept` | [SonarCloud](https://sonarcloud.io/project/issues?open=AY3k4v9ZXMcagTJBbG4b&id=ndsev_zserio)
StringView.h | 54 | `BasicStringView(const const_pointer str) noexcept` | [SonarCloud](https://sonarcloud.io/project/issues?open=AY3k4v85XMcagTJBbG3l&id=ndsev_zserio)
StringView.h | 76 | `template <typename ALLOC> constexpr BasicStringView(const std::basic_string<CharT, Traits, ALLOC>& str) noexcept` | [SonarCloud](https://sonarcloud.io/project/issues?open=AY3k4v85XMcagTJBbG3m&id=ndsev_zserio)
UniquePtr.h | 57 | `template <typename ALLOC_U = ALLOC_T> UniquePtrDeleter(const ALLOC_U& allocator)` | [SonarCloud](https://sonarcloud.io/project/issues?open=AY3k4v99XMcagTJBbG5C&id=ndsev_zserio)
UniquePtr.h | 68 | `template <typename ALLOC_U> UniquePtrDeleter(const UniquePtrDeleter<ALLOC_U>& deleter)` | [SonarCloud](https://sonarcloud.io/project/issues?open=AY3k4v99XMcagTJBbG5D&id=ndsev_zserio)

We use implicit constructor in the generated code as well:

Zserio Type | Generated Method | Description
-- | -- | -- 
`bitmask` | Value constructor | This is intended because we need to allow implicit conversion from bitmask value to bitmask.

**Comment by mohammedRafeeque** [comment]
Hello @mikir 
Can resolve the remaining marked exceptional cases just prefixing "explicit" ?

Please check
