### ISSUE TITLE
Fix MISRA C++ 2023 rule 9.3.1 "Conditional statement 'if' in a function 'readBufferFromFile' should be followed by a block"

### ISSUE THREAD

**Issue by mohammedRafeeque** [ndsev/zserio#606]
**Zserio version and language**
Zserio: master branch
Commit hash: https://github.com/ndsev/zserio/commit/4d228036f4cb51199e151292968c8ecacc4924ce
Language: C++
Priority : 2

**Describe the bug**
Check and resolve SCA warning MISRACPP2023-9_3_1-b Conditional statement 'if' in a function 'encodeFloatingPoint' should be followed by a block

See the attached xls for the SCA warning details 
[MISRACPP2023-9_3_1-b_Warning_ZserioRuntime.xlsx](https://github.com/ndsev/zserio/files/15261112/MISRACPP2023-9_3_1-b_Warning_ZserioRuntime.xlsx)

**How to reproduce**
SCA run using MISRA 2023 configuration.

**Expected behavior**
No SCA warnings for MISRA 2023 ruleset

Additional context
N.A

@Roland-Homeier @mikir FYI.

**Comment by mikir** [comment]
Probably SonarCloud rule "Control structures should use curly braces" could be used for this. We will investigate it during the current milestone.

**Comment by mikir** [comment]
We have added curly braces around single statement everywhere in C++ runtime library and in generated C++ code. There are no exceptions.
