### ISSUE TITLE
Fix MISRA C++ 2023 rule 0.1.2 "The value returned by a function shall be used"

### ISSUE THREAD

**Issue by mohammedRafeeque** [ndsev/zserio#607]
**Zserio version and language**
Zserio: master branch
Commit hash: https://github.com/ndsev/zserio/commit/4d228036f4cb51199e151292968c8ecacc4924ce
Language: C++
Priority : 3

**Describe the bug**
Check and resolve SCA warning  MISRACPP2023-0_1_2-a " Unused function's 'put' return value"

See the attached xls for the SCA warning details 
[MISRACPP2023-0_1_2-a_Warning_ZserioRuntime.xlsx](https://github.com/ndsev/zserio/files/15261164/MISRACPP2023-0_1_2-a_Warning_ZserioRuntime.xlsx)

**How to reproduce**
SCA run using MISRA 2023 configuration.

Expected behavior
No SCA warnings for MISRA 2023 ruleset

Additional context
N.A

@Roland-Homeier @mikir FYI.

**Comment by mikir** [comment]
Probably SonarCloud rule "Return value of "nodiscard" functions should not be ignored" could be used for this. We will investigate it during the current milestone.

**Comment by mikir** [comment]
We went through all reported functions where the returned value should be checked. We have added explicit check of returned value wherever it makes sense.

However, there are still some cases where the check does not make sense (e.g. if function returns `*this` to allow subsequent calls). The following list contains all SonarCloud issues which have been **accepted as the exceptions**:

Module | Line | Command | Link
-- | -- | -- | --
BitStreamReader.h | 334 | `std::copy(sourceIt, sourceIt + numBytesToRead, buffer.begin());` | [SonarCloud](https://sonarcloud.io/project/issues?open=AY-WtRByu6UQLhuCLajQ&id=ndsev_zserio)
BitStreamWriter.cpp | 488 | `std::copy(data.begin(), data.end(), m_buffer.begin() + beginBitPosition / 8);` | [SonarCloud](https://sonarcloud.io/project/issues?open=AY-WtQ_6u6UQLhuCLajJ&id=ndsev_zserio)
BitStreamWriter.cpp | 513 | `std::copy(data.begin(), data.begin() + len, m_buffer.data() + beginBitPosition / 8);` | [SonarCloud](https://sonarcloud.io/project/issues?open=AY-WtQ_6u6UQLhuCLajK&id=ndsev_zserio)
BitStreamWriter.h | 260 | `std::copy(buffer.begin(), buffer.begin() + numBytesToWrite, m_buffer.data() + beginBitPosition / 8);` | [SonarCloud](https://sonarcloud.io/project/issues?open=AY-WtRElu6UQLhuCLajo&id=ndsev_zserio)
CppRuntimeException.cpp | 39 | `std::copy(message.begin(), message.end(), m_buffer.begin() + m_len);` | [SonarCloud](https://sonarcloud.io/project/issues?open=AY-WtRAcu6UQLhuCLajL&id=ndsev_zserio)
FileUtil.cpp | 33 | `stream.seekg(0, stream.end);` | [SonarCloud](https://sonarcloud.io/project/issues?open=AY-WtRA1u6UQLhuCLajN&id=ndsev_zserio)
FileUtil.cpp | 35 | `stream.seekg(0);` | [SonarCloud](https://sonarcloud.io/project/issues?open=AY-WtRA1u6UQLhuCLajO&id=ndsev_zserio)
JsonEncoder.cpp | 54 + 9x | `stream.put('"');` | [SonarCloud](https://sonarcloud.io/project/issues?open=AY-WtRCKu6UQLhuCLajR&id=ndsev_zserio)

There are no exceptions in the generated code.

**Comment by mohammedRafeeque** [comment]
Can we add prefix  [[maybe_unused]] to resolve the remaining warning instead of adding to exception list ?

@mikir  Please check

@Roland-Homeier  FYI.

**Comment by Mi-La** [comment]
Hi, note that `[[maybe_unused]]` is C++17 feature but current generator supports C++11.

**Comment by mikir** [comment]
The issue has been reopened and fixed everywhere even if it does make any sense.
