### ISSUE TITLE
Fix MISRA C++ 2023 rule 7.0.6 "Assignment between numeric types shall be appropriate"

### ISSUE THREAD

**Issue by mohammedRafeeque** [ndsev/zserio#608]
**Zserio version and language**
Zserio: master branch
Commit hash: https://github.com/ndsev/zserio/commit/4d228036f4cb51199e151292968c8ecacc4924ce
Language: C++
Priority : 4

**Describe the bug**
Check and resolve SCA warning  MISRACPP2023-7_0_6-a Do not use a value of type 'int' to initialize a variable of type 'uint16_t'

See the attached xls for the SCA warning details 
[MISRACPP2023-7_0_6-a_Warning_ZserioRuntime.xlsx](https://github.com/ndsev/zserio/files/15261187/MISRACPP2023-7_0_6-a_Warning_ZserioRuntime.xlsx)

**How to reproduce**
SCA run using MISRA 2023 configuration.

Expected behavior
No SCA warnings for MISRA 2023 ruleset

Additional context
N.A

@Roland-Homeier @mikir FYI.

**Comment by mikir** [comment]
@mohammedRafeeque, we have tried to find out the corresponding SonarCloud rule or clang-tidy rule. Unfortunatelly, we were not able to find out anything. So, we should discuss how to continue with the rule which we are not able to reproduce.

Besides of that, please check the attached xlsx. For example, there is a finding in `FloatUtil.cpp`, line 159. However, this line is a if clause. Please check it [here](https://github.com/ndsev/zserio/blob/4d228036f4cb51199e151292968c8ecacc4924ce/compiler/extensions/cpp/runtime/src/zserio/FloatUtil.cpp#L159).

**Comment by mohammedRafeeque** [comment]
You are right in FloatUtil.cpp and BitStreamWriter.cpp there format done in local version. So there is a change in line number to mentioned tag version.
Line 159 refers to source code line below
    uint16_t float16Value = static_cast<uint16_t>(sign16Shifted | exponent16Shifted) | significand16;

**Comment by mohammedRafeeque** [comment]
https://github.com/ndsev/zserio/issues/605#issuecomment-2129387337

**Comment by mikir** [comment]
Unfortunately, SonarCloud did not catch anything (clang-tidy and compiler warnings did not catch anything as well). We are not able to reproduce it and we are not going to fix it blindly.

**Comment by mikir** [comment]
It seems that these findings are not relevant. No action is necessary.
