### ISSUE TITLE
Fix MISRA C++ 2023 rule 6.7.2 "Global variables shall not be used"

### ISSUE THREAD

**Issue by mohammedRafeeque** [ndsev/zserio#611]
**Zserio version and language**
Zserio: master branch
Commit hash: https://github.com/ndsev/zserio/commit/4d228036f4cb51199e151292968c8ecacc4924ce
Language: C++
Priority : 7

**Describe the bug**
Check and resolve SCA warning MISRACPP2023-6_7_2-a  Consider encapsulating 'MAX_U32_VALUES' 

See the attached xls for the SCA warning details  
[MISRACPP2023-6_7_2-a_Warning_ZserioRuntime.xlsx](https://github.com/ndsev/zserio/files/15261283/MISRACPP2023-6_7_2-a_Warning_ZserioRuntime.xlsx)
 

**How to reproduce**
SCA run using MISRA 2023 configuration.

Expected behavior
No SCA warnings for MISRA 2023 ruleset

Additional context
N.A

@Roland-Homeier @mikir FYI.

**Additional context**
Provide relevant information about your OS, used Java version, Python version and/or C++ compiler version.

**Comment by mikir** [comment]
We have activated the corresponding SonarCloud rule [C-style casts and "functional notation" casts shall not be used](https://sonarcloud.io/organizations/ndsev/rules?activation=false&open=cpp%3AM23_388&q=global&qprofile=AY7C1tGrF3OalP95-EpQ).

**Comment by mikir** [comment]
Probably, we could move these constants to the private section of the class. It will be a little bit better from the design point of view and it might be that this change will clear out these findings.

**Comment by mikir** [comment]
Although we can move some constants to the private section of the class, we think that all of them are really false positives. The following states in the MISRA rule 6.7.2:

Global variables are:

1. Variables defined in namespace scope; and
2. Class static data members.

This rule does not apply to global variables that are:

1. constexpr; or
2. const and that are initialized through static initialization.

So, const and static initialization should be ok.
