### ISSUE TITLE
Fix for MISRA C++ 2023 rule  MISRACPP2023-6_4_1-c The identifier 'value' hides an identifier declared in class 'optional_holder_base'

### ISSUE THREAD

**Issue by mohammedRafeeque** [ndsev/zserio#612]
**Zserio version and language**
Zserio: master branch
Commit hash: https://github.com/ndsev/zserio/commit/4d228036f4cb51199e151292968c8ecacc4924ce
Language: C++
Priority : 8

**Describe the bug**
Check and resolve SCA warning MISRACPP2023-6_4_1-c The identifier 'value' hides an identifier declared in class 'optional_holder_base'

See the attached xls for the SCA warning details
[MISRACPP2023-6_4_1-c_Warning_ZserioRuntime.xlsx](https://github.com/ndsev/zserio/files/15261304/MISRACPP2023-6_4_1-c_Warning_ZserioRuntime.xlsx)

**How to reproduce**
SCA run using MISRA 2023 configuration.

Expected behavior
No SCA warnings for MISRA 2023 ruleset

Additional context
N.A

@Roland-Homeier @mikir FYI.

**Comment by mikir** [comment]
This issue will solved within the scope of the issue #609 because it is connected to the same MISRA C++ 2023 rule.
