### ISSUE TITLE
Fix for MISRA C++ 2023 rule  MISRACPP2023-15_1_3-a Constructor 'heap_optional_holder' allowing conversion should be made explicit

### ISSUE THREAD

**Issue by mohammedRafeeque** [ndsev/zserio#613]
**Zserio version and language**
Zserio: master branch
Commit hash: https://github.com/ndsev/zserio/commit/4d228036f4cb51199e151292968c8ecacc4924ce
Language: C++
Priority : 9

**Describe the bug**
Check and resolve SCA warning MISRACPP2023-15_1_3-a Constructor 'heap_optional_holder' allowing conversion should be made explicit 

See the attached xls for the SCA warning details 
[MISRACPP2023-15_1_3-a_Warning_ZserioRuntime.xlsx](https://github.com/ndsev/zserio/files/15261319/MISRACPP2023-15_1_3-a_Warning_ZserioRuntime.xlsx)

**How to reproduce**
teps to reproduce the behavior:
SCA run using MISRA 2023 configuration.

Expected behavior
No SCA warnings for MISRA 2023 ruleset

Additional context
N.A

@Roland-Homeier @mikir FYI.

**Comment by mikir** [comment]
This has been solved within the scope of the issue #593.
