### ISSUE TITLE
Fix MISRA C++ 2023 rule 7.0.3 "The numerical value of a character shall not be used"

### ISSUE THREAD

**Issue by mohammedRafeeque** [ndsev/zserio#628]
**Zserio version and language**
Zserio: latest from master
Commit date: 6 days ago (6/4/2024 7:12:28 PM)
Commit hash: https://github.com/ndsev/zserio/commit/b8cc6c0df51cfa60740421c719f3dabfd88e0fb7

**Describe the bug**
2 Misra warnings are getting reported for rule MISRACPP2023-7_0_3-a 

1.    for (char character : value)
2.   m_buffer.at(m_len) = 0; 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mor4kor/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mor4kor/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

SNo | Rule | Severity | Message | Filename | Linenumber
-- | -- | -- | -- | -- | --
1298 | MISRACPP2023-7_0_3-a | 2 | The plain char   type shall be initialized only by character values | /zserio_runtime/zserio/JsonEncoder.cpp | 55
1244 | MISRACPP2023-7_0_3-a | 2 | To the plain char type assign only character values |/zserio_runtime/zserio/CppRuntimeException.cpp | 42

</body>

</html>

Please check possibility of fixing the same.

SCA run using MISRA 2023 configuration.

Expected behavior
No SCA warnings for MISRA 2023 ruleset

Additional context
N.A

@Roland-Homeier @mikir FYI.

**Comment by Mi-La** [comment]
We will enable rule [S810](https://sonarcloud.io/organizations/ndsev/rules?open=cpp%3AS810&rule_key=cpp%3A).

**Comment by mohammedRafeeque** [comment]
In latest main we are still getting 19 warning.

Date:		6 days ago (8/13/2024 1:00:38 PM)
Commit hash:	009d16a2335233f8476980c07f2d7af4867c53d9

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mor4kor/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mor4kor/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


SNo | Rule | Severity | Message | Filename | Linenumber
-- | -- | -- | -- | -- | --
1527 | MISRACPP2023-7_0_3-a | 2 | There shall be   no conversion from type 'char' to type 'unsigned int' | /zserio_runtime/include/roadgraph_reliable/zserio_runtime/zserio/StringConvertUtil.h | 48
1526 | MISRACPP2023-7_0_3-a | 2 | There shall be no conversion from type 'char' to type 'int' | /zserio_runtime/include/roadgraph_reliable/zserio_runtime/zserio/StringConvertUtil.h | 48
1525 | MISRACPP2023-7_0_3-a | 2 | There shall be   no conversion from type 'char' to type 'unsigned long' | /zserio_runtime/include/roadgraph_reliable/zserio_runtime/zserio/StringConvertUtil.h | 48
1524 | MISRACPP2023-7_0_3-a | 2 | There shall be no conversion from type 'unsigned int' to   type 'char' | /zserio_runtime/include/roadgraph_reliable/zserio_runtime/zserio/StringConvertUtil.h | 48
1523 | MISRACPP2023-7_0_3-a | 2 | There shall be   no conversion from type 'int' to type 'char' | /zserio_runtime/include/roadgraph_reliable/zserio_runtime/zserio/StringConvertUtil.h | 48
1522 | MISRACPP2023-7_0_3-a | 2 | There shall be no conversion from type 'unsigned long' to   type 'char' | /zserio_runtime/include/roadgraph_reliable/zserio_runtime/zserio/StringConvertUtil.h | 48
1505 | MISRACPP2023-7_0_3-a | 2 | There shall be   no conversion from type 'int' to type 'value_type' | /zserio_runtime/include/roadgraph_reliable/zserio_runtime/zserio/StringConvertUtil.h | 36
1304 | MISRACPP2023-7_0_3-a | 2 | There shall be no conversion from type 'char' to type   'uint8_t' | /zserio_runtime/src/roadgraph_reliable/zserio_runtime/zserio/JsonEncoder.cpp | 92
1300 | MISRACPP2023-7_0_3-a | 2 | There shall be   no conversion from type 'char' to type 'uint8_t' | /zserio_runtime/src/roadgraph_reliable/zserio_runtime/zserio/JsonEncoder.cpp | 91
1295 | MISRACPP2023-7_0_3-a | 2 | There shall be no conversion from type 'char' to type   'uint8_t' | /zserio_runtime/src/roadgraph_reliable/zserio_runtime/zserio/JsonEncoder.cpp | 85
1293 | MISRACPP2023-7_0_3-a | 2 | There shall be   no conversion from type 'char' to type 'int' | /zserio_runtime/src/roadgraph_reliable/zserio_runtime/zserio/JsonEncoder.cpp | 80
1292 | MISRACPP2023-7_0_3-a | 2 | There shall be no conversion from type 'char' to type 'int' | /zserio_runtime/src/roadgraph_reliable/zserio_runtime/zserio/JsonEncoder.cpp | 76
1291 | MISRACPP2023-7_0_3-a | 2 | There shall be   no conversion from type 'char' to type 'int' | /zserio_runtime/src/roadgraph_reliable/zserio_runtime/zserio/JsonEncoder.cpp | 72
1290 | MISRACPP2023-7_0_3-a | 2 | There shall be no conversion from type 'char' to type 'int' | /zserio_runtime/src/roadgraph_reliable/zserio_runtime/zserio/JsonEncoder.cpp | 68
1289 | MISRACPP2023-7_0_3-a | 2 | There shall be   no conversion from type 'char' to type 'int' | /zserio_runtime/src/roadgraph_reliable/zserio_runtime/zserio/JsonEncoder.cpp | 64
1288 | MISRACPP2023-7_0_3-a | 2 | There shall be no conversion from type 'char' to type 'int' | /zserio_runtime/src/roadgraph_reliable/zserio_runtime/zserio/JsonEncoder.cpp | 60
1287 | MISRACPP2023-7_0_3-a | 2 | There shall be   no conversion from type 'char' to type 'int' | /zserio_runtime/src/roadgraph_reliable/zserio_runtime/zserio/JsonEncoder.cpp | 59
1286 | MISRACPP2023-7_0_3-a | 2 | There shall be no conversion from type 'char' to type 'int' | /zserio_runtime/src/roadgraph_reliable/zserio_runtime/zserio/JsonEncoder.cpp | 57
1172 | MISRACPP2023-7_0_3-a | 2 | There shall be   no conversion from type 'char' to type 'uint8_t' | /zserio_runtime/src/roadgraph_reliable/zserio_runtime/zserio/BitStreamWriter.cpp | 506



</body>

</html>

@mikir  Can you please check.

**Comment by mikir** [comment]
We have fixed all issues found by SonarCloud rule [S810](https://sonarcloud.io/organizations/ndsev/rules?open=cpp%3AS810&rule_key=cpp%3AS810).
