### ISSUE TITLE
Fix MISRA C++ 2023 rule 7.0.4 "The operands of bitwise operators and shift operators shall be appropriate"

### ISSUE THREAD

**Issue by mohammedRafeeque** [ndsev/zserio#630]
**Zserio version and language**
Zserio: latest from master
Commit date: 6 days ago (6/4/2024 7:12:28 PM)
Commit hash: https://github.com/ndsev/zserio/commit/b8cc6c0df51cfa60740421c719f3dabfd88e0fb7

**Describe the bug**
2 Misra warnings are getting reported for rule MISRACPP2023-7_0_4-a

1 & 2      return calcHashCodeFirstTerm(seedValue) + static_cast<uint32_t>(unsignedValue ^ (unsignedValue >> 32U));

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mor4kor/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mor4kor/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

SNo | Rule | Severity | Message | Filename | Linenumber
-- | -- | -- | -- | -- | --
1658 | MISRACPP2023-7_0_4-a | 2 | The   right-hand-side operand of bitwise operator '^' should be unsigned |zserio_runtime/zserio/HashCodeUtil.h | 62
1657 | MISRACPP2023-7_0_4-a | 2 | The left-hand-side operand of bitwise operator '^' should   be unsigned |/zserio_runtime/zserio/HashCodeUtil.h | 62

</body>

</html>

Please check possibility of fixing the same.

SCA run using MISRA 2023 configuration.

Expected behavior
No SCA warnings for MISRA 2023 ruleset

Additional context
N.A

@Roland-Homeier @mikir FYI.

**Comment by mohammedRafeeque** [comment]
This 2 warnings are no more getting reported in the latest main and latest run.

We can close this ticket.

**Comment by Mi-La** [comment]
We have rule [S874](https://sonarcloud.io/organizations/ndsev/rules?open=cpp%3AS874&rule_key=cpp%3AS874) enabled, it partially checks the 7.0.4 Misra C++ 2023 rule. Currently it catches nothing.
