### ISSUE TITLE
Fix MISRA C++ 2023 rule 6.7.1 "Local variables shall not have static storage duration"

### ISSUE THREAD

**Issue by mohammedRafeeque** [ndsev/zserio#631]
**Zserio version and language**
Zserio: latest from master
Commit date: 6 days ago (6/4/2024 7:12:28 PM)
Commit hash: https://github.com/ndsev/zserio/commit/b8cc6c0df51cfa60740421c719f3dabfd88e0fb7

**Describe the bug**
2 Misra warnings are getting reported for rule MISRACPP2023-6_7_1-a 

1   static MemoryResource* defaultResource = getNewDeleteResource();
2       static detail::NewDeleteResource newDeleteResource;

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mor4kor/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mor4kor/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

1336 | MISRACPP2023-6_7_1-a | 2 | Do not declare the 'newDeleteResource' local   variable with static storage duration |zserio_runtime/zserio/pmr/NewDeleteResource.cpp | 10
-- | -- | -- | -- | -- | --
1335 | MISRACPP2023-6_7_1-a | 2 | Do not declare the 'defaultResource' local variable with   static storage duration | zserio_runtime/zserio/pmr/MemoryResource.cpp | 17

</body>

</html>

Please check possibility of fixing the same.

SCA run using MISRA 2023 configuration.

Expected behavior
No SCA warnings for MISRA 2023 ruleset

Additional context
N.A

@Roland-Homeier @mikir FYI.

**Comment by mohammedRafeeque** [comment]
Observation : We cannot remove static as the function returning a reference . Can we declare static variable in .h file within class scope to have single instance ?
MemoryResource* getNewDeleteResource() noexcept
{
    static detail::NewDeleteResource newDeleteResource;
    return &newDeleteResource;
}

**Comment by Mi-La** [comment]
I'm afraid that we could get into problems with initialization of such static class variable. This way we ensure that `get_default_resource` returns pointer to already initialized resource even when it's used before main.

**Comment by Mi-La** [comment]
Note that Sonar rule [M23_233](https://sonarcloud.io/organizations/ndsev/rules?open=cpp%3AM23_233&rule_key=cpp%3AM23_233) is enabled and we have **3 accepted issues as an exceptions**:

| Moudle | Line | Command | Link |
| -- | -- | -- | -- |
| AnyHolder.h | 29 | `static int currentTypeId;` | [SonarCloud](https://sonarcloud.io/project/issues?issueStatuses=ACCEPTED&id=ndsev_zserio&open=AY-56eW7596Tm5kG5X_f) |
| MemoryResource.cpp | 17 | `static MemoryResource* defaultResource = getNewDeleteResource();` | [SonarCloud](https://sonarcloud.io/project/issues?issueStatuses=ACCEPTED&id=ndsev_zserio&open=AY-56eQu596Tm5kG5X-i) |
| NewDeleteResource.cpp | 10 | `static detail::NewDeleteResource newDeleteResource;` | [SonarClound](https://sonarcloud.io/project/issues?issueStatuses=ACCEPTED&id=ndsev_zserio&open=AY-56eP8596Tm5kG5X-h) |
