### ISSUE TITLE
Fix MISRA C++ 2023 rule 12.3.1 "The union keyword shall not be used"

### ISSUE THREAD

**Issue by mohammedRafeeque** [ndsev/zserio#633]
**Zserio version and language**
Zserio: latest from master
Commit date: 6 days ago (6/4/2024 7:12:28 PM)
Commit hash: https://github.com/ndsev/zserio/commit/b8cc6c0df51cfa60740421c719f3dabfd88e0fb7

**Describe the bug**
1 Misra warning getting reported

1.   union UntypedHolder 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mor4kor/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mor4kor/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

SNo | Rule | Severity | Message | Filename | Linenumber
-- | -- | -- | -- | -- | --
1677 | MISRACPP2023-12_3_1-a | 2 | The 'union'   keyword shall not be used | /zserio_runtime/include/roadgraph_reliable/zserio_runtime/zserio/AnyHolder.h | 296

</body>

</html>

Please check possibility of fixing the same.

SCA run using MISRA 2023 configuration.

Expected behavior
No SCA warnings for MISRA 2023 ruleset

Additional context
N.A

@Roland-Homeier @mikir FYI.

**Comment by Mi-La** [comment]
The sonar rule [M23_158](https://sonarcloud.io/organizations/ndsev/rules?open=cpp%3AM23_158&rule_key=cpp%3AM23_158) is already enabled and we have a single **accepted issue as an exception**:

| Module | Line | Command | Link |
| -- | -- | -- | -- |
| AnyHolder.h | 296 | `union UntypedHolder` | [SonarCloud](https://sonarcloud.io/project/issues?issueStatuses=ACCEPTED&id=ndsev_zserio&open=AY-56eW7596Tm5kG5X_t) |
