### ISSUE TITLE
Fix MISRA C++ 2023 rule 5.10.1 "User-defined identifiers shall have an appropriate form"

### ISSUE THREAD

**Issue by mohammedRafeeque** [ndsev/zserio#635]
**Zserio version and language**
Zserio: latest from master
Commit date: 6 days ago (6/4/2024 7:12:28 PM)
Commit hash: https://github.com/ndsev/zserio/commit/b8cc6c0df51cfa60740421c719f3dabfd88e0fb7

**Describe the bug**
1 Misra warning getting reported

1.      constexpr ::zserio::StringView operator"" _sv(const char* str, std::size_t len) noexcept

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mor4kor/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mor4kor/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

SNo | Rule | Severity | Message | Filename | Linenumber
-- | -- | -- | -- | -- | --
1396 | MISRACPP2023-5_10_1-e | 2 | Do not precede   the user-defined literal suffix with a space: '_sv' | /zserio_runtime/include/roadgraph_reliable/zserio_runtime/zserio/StringView.h | 1002

</body>

</html>

Please check possibility of fixing the same.

SCA run using MISRA 2023 configuration.

Expected behavior
No SCA warnings for MISRA 2023 ruleset

Additional context
N.A

@Roland-Homeier @mikir FYI.

**Comment by mohammedRafeeque** [comment]
This warning can be removed by removing the space between "" and _sv.
Compiling the changes. Please check below modified src line is syntactically and functionally correct.
constexpr ::zserio::StringView operator""_sv(const char* str, std::size_t len) noexcept

**Comment by Mi-La** [comment]
We couldn't find neither any rule in Sonar nor warning in clang / clang-tidy for this issue, thus we won't be able to catch it if it will occur again. However it makes sense to fix it.
