### ISSUE TITLE
Fix MISRA C++ 2023 rule MISRACPP2023-6_4_1-b Identifier 'add' is hiding other identifier with the same name declared in outer scope

### ISSUE THREAD

**Issue by mohammedRafeeque** [ndsev/zserio#636]
**Zserio version and language**
Zserio: latest from master
Commit date: 6 days ago (6/4/2024 7:12:28 PM)
Commit hash: https://github.com/ndsev/zserio/commit/b8cc6c0df51cfa60740421c719f3dabfd88e0fb7

**Describe the bug**
1 Misra warning getting reported

1.      const uint8_t add = static_cast<uint8_t>(0x01U << numBits);

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mor4kor/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mor4kor/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

SNo | Rule | Severity | Message | Filename | Linenumber
-- | -- | -- | -- | -- | --
1226 | MISRACPP2023-6_4_1-b | 2 | Identifier   'add' is hiding other identifier with the same name declared in outer scope | zserio_runtime/zserio/BitStreamWriter.cpp | 552

</body>

</html>

Please check possibility of fixing the same.

SCA run using MISRA 2023 configuration.

Expected behavior
No SCA warnings for MISRA 2023 ruleset

Additional context
N.A

@Roland-Homeier @mikir FYI.

**Comment by mikir** [comment]
This will be solved within the issue https://github.com/ndsev/zserio/issues/609.

**Comment by mohammedRafeeque** [comment]
We can resolve these warnings by renaming the variable to an unused name.
Example:
MISRACPP2023-6_4_1-a: Rename allocator variable to allocator1
MISRACPP2023-6_4_1-b: Rename outer variable add to different name add_1
MISRACPP2023-6_4_1-c" Rename allocator variable to allocator1 

Verified this by changes locally and warnings are not getting reported after renaming.
