### ISSUE TITLE
Fix MISRA C++ 2023 rule 15.0.1 "Special member functions shall be provided appropriately"

### ISSUE THREAD

**Issue by mohammedRafeeque** [ndsev/zserio#637]
**Zserio version and language**
Zserio: latest from master
Commit date: 6 days ago (6/4/2024 7:12:28 PM)
Commit hash: https://github.com/ndsev/zserio/commit/b8cc6c0df51cfa60740421c719f3dabfd88e0fb7

**Describe the bug**
1 Misra warning getting reported

1.     class CppRuntimeException : public std::exception

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mor4kor/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mor4kor/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

SNo | Rule | Severity | Message | Filename | Linenumber
-- | -- | -- | -- | -- | --
1338 | MISRACPP2023-15_0_1-a | 2 | Class   'CppRuntimeException' shall have a protected non-virtual destructor because   it is not unmovable and used as a public base |zserio_runtime/zserio/CppRuntimeException.h | 20

</body>

</html>

Please check possibility of fixing the same.

SCA run using MISRA 2023 configuration.

Expected behavior
No SCA warnings for MISRA 2023 ruleset

Additional context
N.A

@Roland-Homeier @mikir FYI.

**Comment by Mi-La** [comment]
Since we inherit from `std::exception`, it's impossible to make the destructor protected **non-virtual** and it would be impossible to throw "unmovable" exception.

Also we didn't find an appropriate rule in Sonar - only similar rule which can make sense is: https://sonarcloud.io/organizations/ndsev/rules?open=cpp%3AS1235&rule_key=cpp%3AS1235 (and this rule is fulfilled).
