### ISSUE TITLE
Fix MISRA C++ 2023 rule 19.2.2 "The #include directive shall be followed by either a <filename> or "filename" sequence"

### ISSUE THREAD

**Issue by mohammedRafeeque** [ndsev/zserio#639]
**Zserio version and language**
Zserio: latest from master
Commit date: 6 days ago (6/4/2024 7:12:28 PM)
Commit hash: https://github.com/ndsev/zserio/commit/b8cc6c0df51cfa60740421c719f3dabfd88e0fb7

**Describe the bug**
1 Misra warning getting reported

1.        #include ZSERIO_STANDARD_TYPES_HEADER

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mor4kor/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mor4kor/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

SNo | Rule | Severity | Message | Filename | Linenumber
-- | -- | -- | -- | -- | --
1646 | MISRACPP2023-19_2_2-a | 2 | The #include   directive is followed by neither <filename> nor "filename"   sequence: ZSERIO_STANDARD_TYPES_HEADER | zserio_runtime/zserio/Types.h | 6

</body>

</html>

Please check possibility of fixing the same.

SCA run using MISRA 2023 configuration.

Expected behavior
No SCA warnings for MISRA 2023 ruleset

Additional context
N.A

@Roland-Homeier @mikir FYI.

**Comment by Mi-La** [comment]
Enabled https://sonarcloud.io/organizations/ndsev/rules?open=cpp%3AS956&q=%23include.

**Comment by Mi-La** [comment]
MISRA 2023 allows to have the include file name within a macro. Thus the code is compliant if the ZSERIO_STANDARD_TYPES_HEADER contains correct form of the file name. By default, the macro is not defined and thus it's users responsibility to provide correct argument.

> This rule applies after macro replacement has been performed.
