### ISSUE TITLE
Reading enum values does not work in Python 3.12

### ISSUE THREAD

**Issue by wichert** [ndsev/zserio#644]
**Zserio version and language**
Zserio: 2.14.0
Language: Python

**Describe the bug**

I am trying to read an NDS.Live `SmartLayerTile` instance. In Python 3.11 this works fine. With Python 3.12 it breaks when trying to create an enum instance.  

The relevant part of the traceback is:

```
  File "/Users/wichert.akkerman/Code/sg/ndslive/python/ndslive/smart/v2022_01/types/data_layer_lifetime_type.py", line 29, in from_reader
    return cls(reader.read_bits(8))
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wichert.akkerman/Code/dump-zs/.venv/lib/python3.12/site-packages/zserio/enum.py", line 28, in __call__
    obj = super().__call__(value, names, module=module, qualname=qualname, type=type_, start=start)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: (0, None) is not a valid DataLayerLifetimeType
```

The flow here is interesting. For `DataLayerLifetimeType` the generated code calls to the base class:

```python
    @classmethod
    def from_reader(cls: typing.Type['DataLayerLifetimeType'], reader: zserio.BitStreamReader) -> 'DataLayerLifetimeType':
        return cls(reader.read_bits(8))
```

at this point `reader.read_bits(8)` has returned `0`. Inside `zserio.enum._EnumType` the super class constructor is called:

```python
    def __call__(cls, value, names=None, *, module=None, qualname=None, type_=None, start=1):
        obj = super().__call__(value, names, module=module, qualname=qualname, type=type_, start=start)
```

In Python 3.11 a value lookup is done:

https://github.com/python/cpython/blob/1b0e63c81b54a937b089fe335761cba4a96c8cdf/Lib/enum.py#L713-L714

In Python 3.122 the behavior is a lot more complex: 

https://github.com/python/cpython/blob/89bc912dbe277e96e2c7065e06bf8943ddd58eae/Lib/enum.py#L753-L757

In this case because you pass in `names=None` you override the default `names=_not_given` option, which makes Python conver the value to `(0, None)` here, and then fails to find the value and raise an exception.

**Comment by mikir** [comment]
Yes, thanks for that, you are right. It is really strange that they just did such backward incompatible change in python enums.

In all cases, we have already fixed it within the issue #595 in the current milestone. Will be in the next release.

**Comment by wichert** [comment]
Thanks for the quick response. I'm not sure why I missed the older ticket :(

Is there an ETA for the next release?

**Comment by mikir** [comment]
> Thanks for the quick response. I'm not sure why I missed the older ticket :(

This is really no problem.

> Is there an ETA for the next release?

Actually, it is in September. However, in case of any serious trouble because of this problem, we can make for example a patch release on request.
