### ISSUE TITLE
Optional Fields without Writer Coder Result in Invalid Generated Code

### ISSUE THREAD

**Issue by johannes-wolf** [ndsev/zserio#654]
**Zserio version and language**
Zserio: 2.13.0 (and git master)
Language: C++

**Describe the bug**
Optional fields not depending on another field generate invalid C++ code. 

**How to reproduce**
Schema:
```zs
struct A {
  optional uint32 value;
};
```

Command line options:
```
-withoutWriterCode
```

Generated code contains:
```c++
bool A::isValueUsed() const
{
    return (isValueSet());
    //      ^--- ERROR: is*Set gets generated for `-withWriterCode` only!
}
```

**Expected behaviour**
Valid C++ code should be generated.

**Comment by mikir** [comment]
Many thanks for pointing this out and for your effort! It will be integrated within the current milestone.
