### ISSUE TITLE
Zserio isSet Api Error

### ISSUE THREAD

**Issue by sujunling** [ndsev/zserio#656]
**Zserio version and language**
Zserio: 2.14.0
Language: C++

**Describe the bug**
zserio_runtime\zserio\BuiltInOperators.h:
template <typename BITMASK1, typename BITMASK2>
bool isSet(BITMASK1 bitmaskValue, BITMASK2 requiredMask) {
return (bitmaskValue & requiredMask) == requiredMask;
}

ROAD_RANGE_MAPS=1
ROAD_RANGE_SETS=2
ROAD_RANGE_MAPS| ROAD_RANGE_SETS is 3.
if we set content = ROAD_RANGE_SETS, this if condition cannot be triggered.

![clipboard-202407221959-misx9](https://github.com/user-attachments/assets/abf8f3c0-f699-4917-a207-3540faae6169)
![clipboard-202407222000-pyiei](https://github.com/user-attachments/assets/bd271b9e-aebe-4c54-b722-52e3a2be9c33)

**Comment by fklebert** [comment]
I think this probably more a schema bug, which we have fixed in the meantime.

**Comment by mikir** [comment]
> I think this probably more a schema bug, which we have fixed in the meantime.

Yes, I think as well. I have already sent an e-mail directly to the author with more details.

**Comment by fklebert** [comment]
Closing the issue...
