### ISSUE TITLE
Doc Strings Missing for 'extend' Fields in HTML Documentation

### ISSUE THREAD

**Issue by MisterGC** [ndsev/zserio#668]
Fields defined with the extend keyword in a zserio schema are missing their doc strings in the generated HTML documentation.

Steps to Reproduce:

1. Create a zserio schema with extend fields, including doc strings.
2. Generate the HTML documentation.
3. Observe that the doc strings for extend fields are absent.

Example Schema:

```cpp
struct SomeStruct
{
    /** Some data. */
    ExampleType exampleType;

    /** Some additional data.*/
    extend optional ExampleExtension exampleExtension;
}
```

Zserio Version: 2.15.0
Generated HTML: The doc string for exampleExtension is missing.
Expected Behavior: Doc strings for extend fields should appear in the generated HTML documentation.

**Comment by mikir** [comment]
OK, thanks to point this out. I will put it to the current milestone.
