### ISSUE TITLE
HTML emitter does not show code comment for strings with "extend" keyword

### ISSUE THREAD

**Issue by knebelm** [ndsev/zserio#669]
**Zserio version and language**
Zserio: 2.14.0

**Describe the bug**

If the "extend" keyword is used in a struct, the corresponding code comment is not included in the HTML output of the doc generator. NDS.Live example: http://nds.to/rqd9y
 
Code in Smart > metadata.zs: 
 
````
  /** Metadata of the data layers of the smart layer. */
  extend optional SmartLayerDefinition smartLayerDefinition;
```` 

**How to reproduce**
* Generate documentation for NDS.Live Smart module. 
* Check output.
* Code comment is missing (not present in HTML code).

**Expected behavior**
Code comment is included and visible. 

**Additional context**
Have not checked whether this also happes with other keywords, but I think with optional on its own the code comments are present.

**Comment by mikir** [comment]
Yes, this is a duplicate to #668. I will close this one. Thanks!
