### ISSUE TITLE
Improve HTML documentation for grpc services

### ISSUE THREAD

**Issue by fklebert** [ndsev/zserio#67]
The current HTML that gets generated for the `service` keyword is missing parenthesis around the parameter (request struct).

Example:

zserio def
```
rpc stream Response getSomething(Request);
``` 
generates
```
rpc stream Response getSomething Request; 
```
From my point of view we should add parenthesis around the request struct as we also do with other parameters in the HTML docs.

**Comment by mikir** [comment]
I agree, parenthesis should be there. This is a bug. We will fix it within current milestone.
