### ISSUE TITLE
Consider to implement left shift operator by multiplication in C++

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#671]
The left shift of a signed integer is officially undefined behavior in C++17 and earlier: https://en.cppreference.com/w/cpp/language/operator_arithmetic#Bitwise_shift_operators

In C++20, signed integers are officially two's-complement, so left-shift becomes well defined: https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0907r4.html.

Consider to fix it by generating the following code instead of `a << b`:

```
a * (1 << b);
```

**Comment by Mi-La** [comment]
See also Java spec: https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.19
And Python reference: https://docs.python.org/3/reference/expressions.html#shifting

**Comment by Mi-La** [comment]
Note that it seems that modern compilers can optimize multiplication with power of two:
See [godbolt](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:1,endLineNumber:23,positionColumn:1,positionLineNumber:23,selectionStartColumn:1,selectionStartLineNumber:23,startColumn:1,startLineNumber:23),source:'%23include+%3Ciostream%3E%0A%23include+%3Cstdint.h%3E%0A%23include+%3Cstring%3E%0A%0Aint32_t+func1(int32_t+value,+uint8_t+shift)%0A%7B%0A++++return+value+%3C%3C+shift%3B%0A%7D%0A%0Aint32_t+func2(int32_t+value,+uint8_t+shift)%0A%7B%0A++++return+value+*+(1+%3C%3C+shift)%3B%0A%7D%0A%0Aint+main(int+argc,+char*+argv%5B%5D)%0A%7B%0A++++int32_t+value+%3D+13+%2B+argc%3B%0A++++int32_t+res1+%3D+func1(value,+4)%3B%0A++++int32_t+res2+%3D+func2(value,+5)%3B%0A++++%0A++++return+res1+%2B+res2%3B%0A%7D%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:63.03317535545023,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:clang1910,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-O2',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+clang+19.1.0+(Editor+%231)',t:'0')),k:37.5,l:'4',m:44.479495268138805,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86-64+gcc+14.2',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+clang+19.1.0+(Compiler+%231)',t:'0')),header:(),l:'4',m:55.520504731861195,n:'0',o:'',s:0,t:'0')),k:36.96682464454977,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4).
