### ISSUE TITLE
Add extern keyword into zserio language to support proprietary extensions

### ISSUE THREAD

**Issue by CzB404** [ndsev/zserio#70]
It could be beneficial to have a built in `bitstream` type to support proprietary extensions:
```
struct A
{
    bool flag;
    bitstream ext;
};
```

Currently the easiest to use solution is to have a~n aligned~ byte array:
```
struct A
{
    bool flag;
offsets[@index]: // Edit: this has been added by mistake, please disregard it.
    uint8 ext[];
};
```

~However this forces an alignment that may force me as an implementer to waste bits I otherwise would not want to.~

Edit: The problem is that at the end of the byte array there may be meaningless bits that I don't want to waste.

**Comment by mikir** [comment]
Thanks for issue. Not sure if I understood it correctly. You suggest to introduce new built in `bitstream` type which will contain current bit stream offset? Something like

```
struct A
{
    bitstream offset;
    uint8 ext[];
};
```

which will be the same as the following

```
struct A
{
    uint32 offset;
    offset:
        uint8 ext[];
};
```

**Comment by CzB404** [comment]
(I've made a mistake in the original example, the `offsets[@index]` is not part of the problem.)

In the following solution there are unused bits:
```
struct A
{
    bool flag;
    uint8 ext[];
    // Possible unused bits from serialization of extension data
};
```

Suppose I do not want those bits to be unused.
Then currently the only option I have is the following:
```
struct A
{
    bool flag;
    bool ext[]; // Bit array
};
```
There are two problems with this solution:
1. Looks wierd. Very very wierd.
2. Costly in terms of deserialisation: It deserializes into a zserio::BoolArray, which still has to be then reassembled into a byte array to further deserialize.

So a `bitstream` should act like a bit/bool array when serialized, but as a byte array when deserialized, so then a proprietary extension supplier whould just have to run their own deserialization on the resulting byte array.

**Comment by mikir** [comment]
Ach, ok. Thank you for clarification. I agree that `bool ext[];` or `bit:1 ext[]` looks weird. Besides of that, it's really inefficient to write/read such array bit by bit.

Any many thanks for sharing this idea.

**Comment by fklebert** [comment]
Please implement similar to the solution in the zserio-1 fork using the keyword "extern" for this.

**Comment by mikir** [comment]
New suggestion is to use keyword extern. Example:

```
struct SimpleStructure
{
    bit:3     numberA;
    extern    externalStructure;
    bit:7     numberC;
};
```

For the future, we can think about the following enhancements:

`extern:zserio` - External structure with zserio binary format
`extern:protobuf` - External structure with protobuf binary format
`extern:jpeg` - External image with jpeg binary format
`extern:bits` - Some external structure, just array of bits
`extern:bytes` - Some external structure, just array of bytes
`extern:any` - Some external structure, just array of bits
