### ISSUE TITLE
Modernize CMake configuration

### ISSUE THREAD

**Issue by MisterGC** [ndsev/zserio#82]
Currently the minimum supported version is 2.8.x - this prevents usage of a modern target- and property based configuration style which has been introduced with CMake 3.0.

**Comment by Mi-La** [comment]
Currently `zserio_compiler.jar` requires CMake 3.15+. We should probably use at least this version.

Another important changes on the way:
* from 3.12 -> CMake supports `-j <jobs>` for [parallel build](https://cmake.org/cmake/help/latest/manual/cmake.1.html#cmdoption-cmake-build-parallel)
