### ISSUE TITLE
Improve exception message when trying to access non-present optional field.

### ISSUE THREAD

**Issue by MisterGC** [ndsev/zserio#85]
Trying to access a non-present optional field always leads to an exception with the text 

> "Optional field is not set!"

But if the access is triggered implicitely (for example by generated write methods) this message can be confusing. A better message would be imo: 

> "Tried to access value of non-present optional field < fieldname >."

**Comment by mikir** [comment]
I agree. This unclear message seems to be connected to C++ emitter but we must check all other emitters as well.

**Comment by mikir** [comment]
We have changed the message but without the 'fieldname' in this message.

Reasons is that the OptionalHolder is generic abstraction and does not not anything about field name. So, we would have to add new template parameter into OptionalHolder or to catch this exception in generated code. Both of these two solutions are quite complicated, so we have left it as it is for now.
