### ISSUE TITLE
Name clashing in generated code

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#87]
Because generated field names use underscores, it's possible to name fields (with underscore) which will clash with generated code in C++ and Java. Get the inspiration for solution in Python. But even in python we still can get a clashing for getters/setters. See the list below:

- :heavy_check_mark: CHOICE_UNDEFINED in union can clash with an defined choice when a field is named UNDEFINED
- :heavy_check_mark: Getters/setters/indicators cannot change case in the field name, because field names in structure are case sensitive and a user can use both 'field' an 'Field' as field names.
  `struct S { uint32 field; uint32 Field; };`
- :heavy_check_mark: Struct name can clash with getter / setter / indicator / any public method / any private member
   `struct getField { uint32 field; };`
- :heavy_check_mark: All names based on user input (e.g. field names) shall be prefixed (e.g. with '_') and all internal variables shall be without that prefix
  `struct S { uint32 _in; uint32 _out; };`
  - including member names should be named like `m_field_`
- :heavy_multiplication_x: Sql rows contain null setters which can clash 
  `sql_table T { uint32 field; uint32 nullField; };` - seems to be already fixed
- :heavy_multiplication_x: Sql table cannot be named 'tableRow' since it will crash with auto-generated row for table 'table'
  - we should make the rows inner classes of tables - will be fixed in #66
- :heavy_multiplication_x: Sql table cannot be named 'table'! - will be soleved in #195 
  `sql_database { Table table; }` causes SQL Logic Error because we don't escape table name properly

**Comment by Mi-La** [comment]
`struct S { uint32 field; uint32 Field; };`
By default we use first letter in upper case since it's nicer, but if two fields are clashing, we must keep the case in getters.

**Comment by mikir** [comment]
```struct S { uint32 field; uint32 Field; };```
It would be probably the best just to forbid field names which differ only in case of the first letter. This is not a big restriction  and will make things easier.

**Comment by mikir** [comment]
Because name clashing in generated code could lead potentially to the obscure problem (like one generator won't be able to generate compilable code), we have decided to take the following restrictions:

1. We will forbid field names which differ only in case of the first letter.
2. We will forbid zserio type names (structure names, enum names, ...) which do have small letter at the beginning.

Such restrictions will help us to fix generated code quite easily. If such restrictions become too limited, we can find out another solution (like e.g. automatic renaming) but this will require significant effort.

Btw., protobuf in C++ is not better. It's quite easy to find out message name which will cause uncompilable generated code (e.g. if message name is the same as name of any generated private member) .

**Comment by fklebert** [comment]
Just for clarification of rule no. 1:
Would the following schema be affected by the rule:
`Length length;`
Because this is a construct that we are using quite often...

**Comment by Mi-La** [comment]
This should still work. But the following will be forbidden:
```
struct Test
{
    uint16 length;
    uint32 Length;
};
```

**Comment by fklebert** [comment]
OK. Perfect. Got the idea now! Fully support it :-)

**Comment by Mi-La** [comment]
We should also forbid name clashing between package name and type name:
```
package test;
struct MyType
{};
```
```
package test.MyType;
struct Other
{};
```
The above sample make problems in both C++ and Python. In C++ a namespace will clash with class and in Python the generated `api.py` tries to define two symbols with the same name (`MyType`) and moreover the structure `MyType` cannot be imported.

**Comment by Mi-La** [comment]
Fixes:
* [x] Fix CHOICE_UNDEFINED problem in Java unions
