### ISSUE TITLE
Introduce command line argument to enable "unused warnings"

### ISSUE THREAD

**Issue by fklebert** [ndsev/zserio#9]
The current zserio compiler throws warnings for unused structures. This is basically a good thing to keep an eye on unused parts of the schema.
But of course there will be always one warning we have to ignore, being the one for a root element.

I think the SQLite extension does work with it when using sql_database or sql_table. Those do not trigger warnings.

If we can prefix a structure with a keywork `root` or similar then the zserio compiler would not need to throw the warning.

**Comment by Mi-La** [comment]
The idea is good, but we should solve syntax and wrong usage:

**Possible syntaxes:**
1. `root struct Root { ... };`
1. `struct root Root { ... };`
1. `main struct Root { ... };`
1. `struct main Root { ... };`
1. `rootstruct Root { ... };`
1. `mainstruct Root { ... };`
1. `root Root;`
    `struct Root { ... };`
1. `main Root;`
    ` struct Root { ... };`
1. `struct Root^ { ... };`

**Wrong usage:**
`root struct MarkedRoot

**Comment by fklebert** [comment]
Initial idea was to use something like
```
root struct Element1
{}
```
The above would not throw the warning for unused element. But the element itself could of course be reused by other structs. So basically there would be no "wrong usage" at all.

**Comment by Mi-La** [comment]
We think that root keyword isn't consistent enough. For example, it seems very strange to have `root const string ID = "Zserio"`, or `root subtype int32 MySubtype`. And also for users it might be difficult to keep in mind which entities can be "root" - e.g. `sql_database` or `service` are always "root".

Therefore we propose to introduce new command line option -> `-withUnusedWarnings` / `-withoutUnusedWarnings(default)`. Then the user can just run the tool with `-witUnusedWarnings` to check which types are not used. In future, we could add something like "unusedWarningsBlackList" to suppress the warning for types which are supposed to be "root". This solution will not do mess in the language.

**Comment by fklebert** [comment]
OK, I agree. So the default would be that the tool does not provide the unused warnings. Only if you explicitly turn it on. Sounds good!

**Comment by Mi-La** [comment]
yes, by default you get no unused warnings
