### ISSUE TITLE
Add server and client stubs for GRPC generated classes

### ISSUE THREAD

**Issue by fklebert** [ndsev/zserio#90]
It would be very beneficial to add stubs for client and server implementation on top of the generated code for GRCP.

C++ Example (derived from some real implementation, so please ignore any copy/paste/edit errors; I hope it gives a hint of what I mean):
```
#include <gen/generatedService.h>
#include <memory>

namespace gen
{
class GeneratedServiceServer: public gen::GeneratedService::Service
{

public:
    GeneratedServiceServer();
    ~GeneratedServiceServer() override;

    grpc::Status getServiceDefinition(grpc::ServerContext *context,
                                      const gen::Empty *request,
                                      gen::SomeDefinition *response) override;

private:
    class Impl;
    std::unique_ptr<Impl> impl_;
};
}
```

**Comment by Mi-La** [comment]
Lets assume C++ (it's very similar in other languages):
Currently the "stubs" are the `GeneratedService::Service` for server and `GeneratedService::Stub` (returned by `GeneratedService::NewStub()`). User only have to override methods  defined in the `Service` class to implements the service and call the method on `Stub` (either synchronously or asynchronously). Please see the [SimpleServiceTest](https://github.com/ndsev/zserio/blob/master/test/language/service_types/cpp/SimpleServiceTest.cpp) test for reference.

It's not clear what do you imagine as the new "stubs". There are more ways how to create the server and client's channel and how to establish the communication (e.g. insecure connection/secure connection/in-process) and there are maybe more implementations of the server itself.

**Comment by fklebert** [comment]
> User only have to override methods defined in the Service class to implements the service and call the method on Stub (either synchronously or asynchronously).

This is exactly the issue that I wanted to address. It may not be clear for everyone exactly what to do. That is why I opted for generating a stub that does the override and add `//TODO: add you code comments` in all method bodies there.

It is not really important to do this. More a convenience thing than anything.

**Comment by mikir** [comment]
We have redesigned whole service interface. The issue become obsolete.
